#pragma once

#define TRAINER_ROLV_1         1
#define TRAINER_THERESA        2
#define TRAINER_MIGUEL_1       3
#define TRAINER_FRANKLIN       4
#define TRAINER_MARVIN         5
#define TRAINER_TOMAS          6
#define TRAINER_VITRUVIO       7
#define TRAINER_BELDUM         8
#define TRAINER_METEOR_1       9
#define TRAINER_TOMU           10
#define TRAINER_SHIRASAGI      11
#define TRAINER_NAOTA          12
#define TRAINER_PAOLO          13
#define TRAINER_NIIZUMA        14
#define TRAINER_WATTSON_1      15
#define TRAINER_WATTSON_2      16
#define TRAINER_FOOTMAN_1      17
#define TRAINER_AKATSUKI       18
#define TRAINER_MIKOV_1        19
#define TRAINER_BOBOV_1        20
#define TRAINER_GUNKOV_1       21
#define TRAINER_KARKOV_1       22
#define TRAINER_ROBOTNOV_1     23
#define TRAINER_ROLV_2         24
#define TRAINER_SPUTNOV_1      25
#define TRAINER_VLADOV_1       26
#define TRAINER_ADOLV_1        27
#define TRAINER_ASIMOV_1       28
#define TRAINER_LIAM           29
#define TRAINER_LIZZIE         30
#define TRAINER_MIKOV_2        31
#define TRAINER_BOBOV_2        32
#define TRAINER_GUNKOV_2       33
#define TRAINER_KARKOV_2       34
#define TRAINER_ROBOTNOV_2     35
#define TRAINER_ED             36
#define TRAINER_TESRAEL        37
#define TRAINER_LILY           38
#define TRAINER_RAN_MAO        39
#define TRAINER_SPUTNOV_2      40
#define TRAINER_VLADOV_2       41
#define TRAINER_ADOLV_2        42
#define TRAINER_ASIMOV_2       43
#define TRAINER_CRANKSHAFT     44
#define TRAINER_ZAPPIZOR       45
#define TRAINER_ARTURO         46
#define TRAINER_DOUBLEACT_1    47
#define TRAINER_GAOLER_1       48
#define TRAINER_GAOLER_2       49
#define TRAINER_MALFEASANCE    50
#define TRAINER_TINAANDBRUCE_1 51
#define TRAINER_TINAANDBRUCE_2 52
#define TRAINER_TINAANDBRUCE_3 53
#define TRAINER_TINAANDBRUCE_4 54
#define TRAINER_TINAANDBRUCE_5 55
#define TRAINER_TINAANDBRUCE_6 56
#define TRAINER_DUBLIQUE       57
#define TRAINER_MIKE           58
#define TRAINER_GWEN           59
#define TRAINER_CARMEN         60
#define TRAINER_GENGUI         61
#define TRAINER_RICKY_1        62
#define TRAINER_LOLA           63
#define TRAINER_BUCCHA         64
#define TRAINER_SIMON          65
#define TRAINER_MACGUFFIN      66
#define TRAINER_RICKY_2        67
#define TRAINER_LOLIDRAGON     68
#define TRAINER_LIRIACHEN      69
#define TRAINER_MCDOUGAL       70
#define TRAINER_RANDALL        71
#define TRAINER_PARKER         72
#define TRAINER_GEORGE         73
#define TRAINER_BERKE          74
#define TRAINER_MAJIDE         75
#define TRAINER_VINCENT        76
#define TRAINER_LEROY          77
#define TRAINER_ICHI           78
#define TRAINER_MANGOMAN       79
#define TRAINER_ALBERTO        80
#define TRAINER_ENIGMA         81
#define TRAINER_CORLEONE       82
#define TRAINER_CASTANO        83
#define TRAINER_FIVENINJA_1    84
#define TRAINER_INIGO          85
#define TRAINER_MANFRED_1      86
#define TRAINER_WILTON         87
#define TRAINER_GIMLETEYE      88
#define TRAINER_MARY           89
#define TRAINER_LORI           90
#define TRAINER_JODY           91
#define TRAINER_MEI_RIN        92
#define TRAINER_ELAINE         93
#define TRAINER_JEMIMA         94
#define TRAINER_BLAIRWITCH     95
#define TRAINER_BETHANY        96
#define TRAINER_FISHGIRL_1     97
#define TRAINER_SUSAN          98
#define TRAINER_FIVENINJA_2    99
#define TRAINER_JULIANNE       100
#define TRAINER_BROOKE         101
#define TRAINER_WHITNEY        102
#define TRAINER_MARLENE        103
#define TRAINER_MIKOV_3        104
#define TRAINER_PATRICIA       105
#define TRAINER_RUBRIC         106
#define TRAINER_TCHAIKOVSKY    107
#define TRAINER_TABBY          108
#define TRAINER_BILLSTOKEY     109
#define TRAINER_VALERIE        110
#define TRAINER_BOBOV_3        111
#define TRAINER_GUNKOV_3       112
#define TRAINER_KARKOV_3       113
#define TRAINER_TILLY          114
#define TRAINER_DANI           115
#define TRAINER_BRIANNA        116
#define TRAINER_CINDY          117
#define TRAINER_ROBOTNOV_3     118
#define TRAINER_ANETTE         119
#define TRAINER_ROLV_3         120
#define TRAINER_SPUTNOV_3      121
#define TRAINER_VLADOV_3       122
#define TRAINER_ADOLV_3        123
#define TRAINER_WEISHI         124
#define TRAINER_CHAOYUN        125
#define TRAINER_SHUYI          126
#define TRAINER_HIRO           127
#define TRAINER_CONNIE         128
#define TRAINER_BRIDGET        129
#define TRAINER_OLIVIA         130
#define TRAINER_TIFFANY        131
#define TRAINER_JESSICA        132
#define TRAINER_ASIMOV_3       133
#define TRAINER_BARBARA        134
#define TRAINER_MIMI           135
#define TRAINER_RICHIE         136
#define TRAINER_OROBAS         137
#define TRAINER_GARRET         138
#define TRAINER_WINSTON_1      139
#define TRAINER_DUNCAN         140
#define TRAINER_DIRTHUGGER     141
#define TRAINER_BIFBOFBEE_1    142
#define TRAINER_STEVE_1        143
#define TRAINER_CHRIS          144
#define TRAINER_MACHI          145
#define TRAINER_KENN           146
#define TRAINER_STEVE_2        147
#define TRAINER_ROLV_4         148
#define TRAINER_EOWYN          149
#define TRAINER_BRUNELLA       150
#define TRAINER_LUIS           151
#define TRAINER_VEGAS          152
#define TRAINER_PEKABO         153
#define TRAINER_TARQUIN        154
#define TRAINER_MIKHAIL        155
#define TRAINER_JACKABY        156
#define TRAINER_MATTHEW        157
#define TRAINER_ERLANDU        158
#define TRAINER_PETRUCHIO      159
#define TRAINER_OBLIGATION     160
#define TRAINER_CODY           161
#define TRAINER_STAN           162
#define TRAINER_CHUCKLES       163
#define TRAINER_SEAMUSII       164
#define TRAINER_BIFBOFBEE_2    165
#define TRAINER_GONZALES       166
#define TRAINER_SHUNKLE        167
#define TRAINER_BENJI          168
#define TRAINER_DONATELLO      169
#define TRAINER_MUSHUSHSHU     170
#define TRAINER_DANNY          171
#define TRAINER_FUNHOUSE       172
#define TRAINER_DUDLEY         173
#define TRAINER_CHAD           174
#define TRAINER_TONY           175
#define TRAINER_FOOTMAN_2      176
#define TRAINER_MANFRED_2      177
#define TRAINER_KERRI          178
#define TRAINER_KONGAMOTO      179
#define TRAINER_FINALSMASH     180
#define TRAINER_HATSUHARU      181
#define TRAINER_ICHIROU        182
#define TRAINER_NOB            183
#define TRAINER_MARY_SUE       184
#define TRAINER_ALCAPONE       185
#define TRAINER_ANJOU          186
#define TRAINER_MISSY          187
#define TRAINER_YUJI           188
#define TRAINER_DAISUKE        189
#define TRAINER_ZACHARY        190
#define TRAINER_KIRK           191
#define TRAINER_SCOTT          192
#define TRAINER_HARVEY_1       193
#define TRAINER_SHAWN          194
#define TRAINER_RANDY          195
#define TRAINER_DALTON         196
#define TRAINER_BESS           197
#define TRAINER_TOHRU          198
#define TRAINER_KYOU           199
#define TRAINER_YUKI           200
#define TRAINER_YONGLIANG      201
#define TRAINER_FLINT          202
#define TRAINER_TINGFENG       203
#define TRAINER_JAKE           204
#define TRAINER_GUIREN         205
#define TRAINER_BERNIE_1       206
#define TRAINER_LONGWEI        207
#define TRAINER_BERNIE_2       208
#define TRAINER_MIKOV_4        209
#define TRAINER_BOBOV_4        210
#define TRAINER_KEN            211
#define TRAINER_HAYATE         212
#define TRAINER_WESTLEY        213
#define TRAINER_SHANE          214
#define TRAINER_JUSTIN         215
#define TRAINER_CHINBAO        216
#define TRAINER_JEFF           217
#define TRAINER_HORODA         218
#define TRAINER_ETHAN          219
#define TRAINER_GAOLER_3       220
#define TRAINER_BRAVO          221
#define TRAINER_MINA           222
#define TRAINER_BRENT          223
#define TRAINER_DONALD         224
#define TRAINER_TAYLOR         225
#define TRAINER_CHIKICORMA     226
#define TRAINER_DEREK          227
#define TRAINER_HATORI         228
#define TRAINER_MOMIJI         229
#define TRAINER_BRANDON        230
#define TRAINER_GUNKOV_4       231
#define TRAINER_EDWARD         232
#define TRAINER_AQUIFER        233
#define TRAINER_THUNDORA       234
#define TRAINER_MONS           235
#define TRAINER_DONPUNCHIES    236
#define TRAINER_JOSHUA         237
#define TRAINER_YVES           238
#define TRAINER_CAMERON_1      239
#define TRAINER_CAMERON_2      240
#define TRAINER_CAMERON_3      241
#define TRAINER_CAMERON_4      242
#define TRAINER_FOOTMAN_3      243
#define TRAINER_VENTANA        244
#define TRAINER_GAIA           245
#define TRAINER_FLAMMA         246
#define TRAINER_CHERIE         247
#define TRAINER_ALEXIS         248
#define TRAINER_SHUBITZ        249
#define TRAINER_JACKI_1        250
#define TRAINER_GLEIS_1        251
#define TRAINER_JACKI_2        252
#define TRAINER_TEX            253
#define TRAINER_WINSTON_2      254
#define TRAINER_TUCKER         255
#define TRAINER_THOMAS         256
#define TRAINER_WALTER         257
#define TRAINER_KARKOV_4       258
#define TRAINER_ROBOTNOV_4     259
#define TRAINER_ROLV_5         260
#define TRAINER_CAITLIN        261
#define TRAINER_BENNY_1        262
#define TRAINER_GLACIA         263
#define TRAINER_INDIGO         264
#define TRAINER_ROXANNE        265
#define TRAINER_HARUKO         266
#define TRAINER_WATTSON_3      267
#define TRAINER_VERACITY       268
#define TRAINER_NORMAN         269
#define TRAINER_WINONA         270
#define TRAINER_TATEANDLIZA    271
#define TRAINER_ESAU           272
#define TRAINER_MORPH_1        273
#define TRAINER_TED            274
#define TRAINER_PAUL           275
#define TRAINER_MORPH_2        276
#define TRAINER_JERRY          277
#define TRAINER_NOTTINGHAM     278
#define TRAINER_BANDITO        279
#define TRAINER_SCISSORA       280
#define TRAINER_GEORGIA        281
#define TRAINER_KAREN          282
#define TRAINER_FOOTMAN_4      283
#define TRAINER_FOOTMAN_5      284
#define TRAINER_FIVENINJA_3    285
#define TRAINER_JADEANDSARA    286
#define TRAINER_KATANDBERT     287
#define TRAINER_ANNAANDMEG_1   288
#define TRAINER_SASHA          289
#define TRAINER_DOUBLEACT_2    290
#define TRAINER_ANNAANDMEG_2   291
#define TRAINER_MUGWIN_1       292
#define TRAINER_MIGUEL_2       293
#define TRAINER_COLTON         294
#define TRAINER_CHLOE_1        295
#define TRAINER_FISHGIRL_2     296
#define TRAINER_MANZANA        297
#define TRAINER_MIGUEL_3       298
#define TRAINER_MUGWIN_2       299
#define TRAINER_UGBUOON        300
#define TRAINER_MARISSA        301
#define TRAINER_ROCKIT         302
#define TRAINER_ISABEL_1       303
#define TRAINER_ISABEL_2       304
#define TRAINER_TARNATION      305
#define TRAINER_HANNAH         306
#define TRAINER_GUARDIAN       307
#define TRAINER_CHLOE_2        308
#define TRAINER_PERKINS        309
#define TRAINER_MAGDALENE      310
#define TRAINER_TIMOTHY        311
#define TRAINER_MUGWIN_3       312
#define TRAINER_QINGXUE        313
#define TRAINER_SHELBY_1       314
#define TRAINER_KATHY          315
#define TRAINER_SHELBY_2       316
#define TRAINER_SHELBY_3       317
#define TRAINER_CALVIN_1       318
#define TRAINER_LAURENCE       319
#define TRAINER_JOSH           320
#define TRAINER_TOMMY          321
#define TRAINER_ASMODEUS       322
#define TRAINER_BEN            323
#define TRAINER_BELIAL_1       324
#define TRAINER_KEVIN          325
#define TRAINER_NEAL           326
#define TRAINER_FOOTMAN_6      327
#define TRAINER_CALVIN_2       328
#define TRAINER_CALVIN_3       329
#define TRAINER_CLINT          330
#define TRAINER_SENEX_1        331
#define TRAINER_EDDIE          332
#define TRAINER_ALLEN          333
#define TRAINER_FOOTMAN_7      334
#define TRAINER_FENGLEI        335
#define TRAINER_TIMANDTINA     336
#define TRAINER_DUNSTAN        337
#define TRAINER_FOOTMAN_8      338
#define TRAINER_SMASHSHOT      339
#define TRAINER_NED            340
#define TRAINER_MASHIMA        341
#define TRAINER_FOOTMAN_9      342
#define TRAINER_FERNANDO       343
#define TRAINER_OSWALD         344
#define TRAINER_RICARDO        345
#define TRAINER_ELLIOT_1       346
#define TRAINER_TEMULENCE_1    347
#define TRAINER_ELLIOT_2       348
#define TRAINER_FIVENINJA_4    349
#define TRAINER_UNBONE         350
#define TRAINER_JACOB          351
#define TRAINER_ANTHONY        352
#define TRAINER_BENJAMIN_1     353
#define TRAINER_BENJAMIN_2     354
#define TRAINER_BENJAMIN_3     355
#define TRAINER_BENJAMIN_4     356
#define TRAINER_BENJAMIN_5     357
#define TRAINER_ABIGAIL_1      358
#define TRAINER_JASMINE        359
#define TRAINER_ABIGAIL_2      360
#define TRAINER_ABIGAIL_3      361
#define TRAINER_ABIGAIL_4      362
#define TRAINER_ABIGAIL_5      363
#define TRAINER_HEIWAJIMA      364
#define TRAINER_DYLAN_1        365
#define TRAINER_DYLAN_2        366
#define TRAINER_DYLAN_3        367
#define TRAINER_DYLAN_4        368
#define TRAINER_MARIA_1        369
#define TRAINER_WAYNE          370
#define TRAINER_WOODY          371
#define TRAINER_MARIA_2        372
#define TRAINER_MARIA_3        373
#define TRAINER_MONKLEY        374
#define TRAINER_THESHERIFF     375
#define TRAINER_CYRUS          376
#define TRAINER_MANLYHERO      377
#define TRAINER_HUNKY_DORY     378
#define TRAINER_ISAIAH_1       379
#define TRAINER_ISAIAH_2       380
#define TRAINER_ISAIAH_3       381
#define TRAINER_MAGNUSVII      382
#define TRAINER_METEOR_2       383
#define TRAINER_MAXINE         384
#define TRAINER_METEOR_3       385
#define TRAINER_PERJURY        386
#define TRAINER_MARIEBAIN      387
#define TRAINER_KATELYN_1      388
#define TRAINER_KATELYN_2      389
#define TRAINER_KATELYN_3      390
#define TRAINER_KATELYN_4      391
#define TRAINER_NICOLAS_1      392
#define TRAINER_NICOLAS_2      393
#define TRAINER_NICOLAS_3      394
#define TRAINER_NICKYP         395
#define TRAINER_FORTUNO        396
#define TRAINER_LIUBEI         397
#define TRAINER_JAIME          398
#define TRAINER_HUGHIE         399
#define TRAINER_PHILIP         400
#define TRAINER_JARED          401
#define TRAINER_MITCHELL       402
#define TRAINER_TANNER         403
#define TRAINER_WILL           404
#define TRAINER_MAYBEWITCH     405
#define TRAINER_BADFAIRY       406
#define TRAINER_BENNY_2        407
#define TRAINER_HESTER         408
#define TRAINER_GLEIS_2        409
#define TRAINER_TEMULENCE_2    410
#define TRAINER_ROBERT         411
#define TRAINER_BURKE          412
#define TRAINER_OSTAFAN        413
#define TRAINER_DECKARD        414
#define TRAINER_ROGER          415
#define TRAINER_BRET           416
#define TRAINER_MAKOTO         417
#define TRAINER_HIDEO          418
#define TRAINER_TANCRED        419
#define TRAINER_CHARLES        420
#define TRAINER_LAO_1          421
#define TRAINER_LAO_2          422
#define TRAINER_SCHWARTZ_1     423
#define TRAINER_SCHWARTZ_2     424
#define TRAINER_TYRONE         425
#define TRAINER_MATTEO         426
#define TRAINER_LAURA          427
#define TRAINER_CORA           428
#define TRAINER_JILL           429
#define TRAINER_CYNDY_1        430
#define TRAINER_CYNDY_2        431
#define TRAINER_SCHWARTZ_3     432
#define TRAINER_SCHWARTZ_4     433
#define TRAINER_VINNIE         434
#define TRAINER_ANGELWITCH     435
#define TRAINER_EASTWITCH      436
#define TRAINER_MADELINE_1     437
#define TRAINER_STANISLAUS     438
#define TRAINER_BOSS           439
#define TRAINER_MADELINE_2     440
#define TRAINER_BEVERLY        441
#define TRAINER_DAWN           442
#define TRAINER_BEATRICE       443
#define TRAINER_DENISE         444
#define TRAINER_BETH           445
#define TRAINER_KRIS           446
#define TRAINER_JESUS          447
#define TRAINER_ALICE          448
#define TRAINER_WORCESTERIA    449
#define TRAINER_HUAJIAO        450
#define TRAINER_TANYA          451
#define TRAINER_SHARON         452
#define TRAINER_ENDLESS        453
#define TRAINER_KOTOKABE       454
#define TRAINER_CATALANA       455
#define TRAINER_CREPERIE       456
#define TRAINER_DONGIGA        457
#define TRAINER_DANAPIX        458
#define TRAINER_ERIN           459
#define TRAINER_MEADOWBREAK    460
#define TRAINER_BAKANEKO       461
#define TRAINER_KAYLEE         462
#define TRAINER_BALBOON        463
#define TRAINER_DARCY          464
#define TRAINER_JENNY_1        465
#define TRAINER_JENNY_2        466
#define TRAINER_JENNY_3        467
#define TRAINER_JENNY_4        468
#define TRAINER_NAKAJIMA       469
#define TRAINER_SHIZUO         470
#define TRAINER_LENNA          471
#define TRAINER_FOOTMAN_10     472
#define TRAINER_MARTHA         473
#define TRAINER_YONGSHUI       474
#define TRAINER_NINA           475
#define TRAINER_RYUUGAMINE     476
#define TRAINER_DIANA_1        477
#define TRAINER_DIANA_2        478
#define TRAINER_DIANA_3        479
#define TRAINER_DIANA_4        480
#define TRAINER_AKAGI          481
#define TRAINER_AMYANDLIV_1    482
#define TRAINER_DOUGANDLOLA    483
#define TRAINER_MIRAI          484
#define TRAINER_AMYANDLIV_2    485
#define TRAINER_GINAANDMIA     486
#define TRAINER_AMYANDLIV_3    487
#define TRAINER_AMYANDLIV_4    488
#define TRAINER_AMYANDLIV_5    489
#define TRAINER_PIOUS          490
#define TRAINER_BARRABAS       491
#define TRAINER_ERNEST_1       492
#define TRAINER_DWAYNE         493
#define TRAINER_PHILLIP        494
#define TRAINER_LEONARD        495
#define TRAINER_FORMAGGIO      496
#define TRAINER_ERNEST_2       497
#define TRAINER_ERNEST_3       498
#define TRAINER_ERNEST_4       499
#define TRAINER_ERNEST_5       500
#define TRAINER__1             501
#define TRAINER__2             502
#define TRAINER__3             503
#define TRAINER_SONNY          504
#define TRAINER_DONOVAN        505
#define TRAINER_GERALD         506
#define TRAINER_KELVIN         507
#define TRAINER_KODY           508
#define TRAINER_TEVIN          509
#define TRAINER_DAMON          510
#define TRAINER_PABLO          511
#define TRAINER_FOOTMAN_11     512
#define TRAINER_HECTOR_1       513
#define TRAINER_HECTOR_2       514
#define TRAINER_EDWIN_1        515
#define TRAINER_EDWIN_2        516
#define TRAINER_EDWIN_3        517
#define TRAINER_EDWIN_4        518
#define TRAINER_TEMULENCE_3    519
#define TRAINER_BERT           520
#define TRAINER_BRENDAN_1      521
#define TRAINER_BRENDAN_2      522
#define TRAINER_BRENDAN_3      523
#define TRAINER_BRENDAN_4      524
#define TRAINER_BRENDAN_5      525
#define TRAINER_BRENDAN_6      526
#define TRAINER_BRENDAN_7      527
#define TRAINER_BRENDAN_8      528
#define TRAINER_ALICIA_UNKNOWN 529
#define TRAINER_ALICIA_1       530
#define TRAINER_ALICIA_2       531
#define TRAINER_WAR            532
#define TRAINER_MAY_1          533
#define TRAINER_MAY_2          534
#define TRAINER_MAY_3          535
#define TRAINER_MAY_4          536
#define TRAINER_MAY_5          537
#define TRAINER_ISAAC_1        538
#define TRAINER_RILEY          539
#define TRAINER_AIDAN          540
#define TRAINER_ISAAC_2        541
#define TRAINER_ISAAC_3        542
#define TRAINER_ISAAC_4        543
#define TRAINER_ISAAC_5        544
#define TRAINER_HIROAKI        545
#define TRAINER_ALEXIA         546
#define TRAINER_DANIELLE       547
#define TRAINER_LYDIA_1        548
#define TRAINER_LYDIA_2        549
#define TRAINER_LYDIA_3        550
#define TRAINER_LYDIA_4        551
#define TRAINER_YULVARIN       552
#define TRAINER_SWINEWITCH     553
#define TRAINER_SEBASTIAN      554
#define TRAINER_JACKSON_1      555
#define TRAINER_JACKSON_2      556
#define TRAINER_JACKSON_3      557
#define TRAINER_JACKSON_4      558
#define TRAINER_CATHERINE_1    559
#define TRAINER_TOOTHWITCH     560
#define TRAINER_SOPHIA         561
#define TRAINER_CATHERINE_2    562
#define TRAINER_SALARYMAN_1    563
#define TRAINER_CATHERINE_3    564
#define TRAINER_CATHERINE_4    565
#define TRAINER_TEMULENCE_4    566
#define TRAINER_FOOTMAN_12     567
#define TRAINER_SALARYMAN_2    568
#define TRAINER_FOOTMAN_13     569
#define TRAINER_SALARYMAN_3    570
#define TRAINER_GRUNT_1        571
#define TRAINER_GRUNT_2        572
#define TRAINER_GRUNT_3        573
#define TRAINER_GRUNT_4        574
#define TRAINER_ZABULON        575
#define TRAINER_GRUNT_5        576
#define TRAINER_GRUNT_6        577
#define TRAINER_GRUNT_7        578
#define TRAINER_GRUNT_8        579
#define TRAINER_GRUNT_9        580
#define TRAINER_BELIAL_2       581
#define TRAINER_MIGHT          582
#define TRAINER_GRUNT_10       583
#define TRAINER_GRUNT_11       584
#define TRAINER_GRUNT_12       585
#define TRAINER_GRUNT_13       586
#define TRAINER_GRUNT_14       587
#define TRAINER_GRUNT_15       588
#define TRAINER_GRUNT_16       589
#define TRAINER_GRUNT_17       590
#define TRAINER_LINDA          591
#define TRAINER_SALARYMAN_4    592
#define TRAINER_SALARYMAN_5    593
#define TRAINER_KENT           594
#define TRAINER_PESTILENCE     595
#define TRAINER_SALARYMAN_6    596
#define TRAINER_TABITHA        597
#define TRAINER_SHADERU        598
#define TRAINER_GLEIS_3        599
#define TRAINER_COURTNEY       600
#define TRAINER_MAXIE_1        601
#define TRAINER_MAXIE_2        602
#define TRAINER_TIANA          603
#define TRAINER_HARVEY_2       604
#define TRAINER_JANICE         605
#define TRAINER_MUGWIN_4       606
#define TRAINER_HALEY_1        607
#define TRAINER_HALEY_2        608
#define TRAINER_HALEY_3        609
#define TRAINER_HALEY_4        610
#define TRAINER_SALLY          611
#define TRAINER_ROBIN          612
#define TRAINER_ANDREA         613
#define TRAINER_CRISSY         614
#define TRAINER_RICA           615
#define TRAINER_LYLE           616
#define TRAINER_JOSE           617
#define TRAINER_DOUG           618
#define TRAINER_TOMMO          619
#define TRAINER_CINNABAR       620
#define TRAINER_ANDROMALIUS    621
#define TRAINER_JAMES_1        622
#define TRAINER_FLOATZEL       623
#define TRAINER_JAMES_2        624
#define TRAINER_JAMES_3        625
#define TRAINER_KLOTHOK        626
#define TRAINER_RAAKOR         627
#define TRAINER_LENNY          628
#define TRAINER_LUCAS_1        629
#define TRAINER_ALAN           630
#define TRAINER_CLARK          631
#define TRAINER_FENGDARIN      632
#define TRAINER_LUCAS_2        633
#define TRAINER_BRENTFORD      634
#define TRAINER_HERO           635
#define TRAINER_TRENT_1        636
#define TRAINER_ZUUL           637
#define TRAINER_KYLIE          638
#define TRAINER_TRENT_2        639
#define TRAINER_MAIANDHIRO     640
#define TRAINER_LEAANDJED      641
#define TRAINER_LOLAANDLUTE    642
#define TRAINER_LOISANDHAL_1   643
#define TRAINER_LOISANDHAL_2   644
#define TRAINER_LOISANDHAL_3   645
#define TRAINER_LOISANDHAL_4   646
#define TRAINER_JOHANNA        647
#define TRAINER_MEILIN         648
#define TRAINER_VIVIAN         649
#define TRAINER_NIANZHU        650
#define TRAINER_SIOBHAN        651
#define TRAINER_WITCH          652
#define TRAINER_SANDWITCH      653
#define TRAINER_ASPHODEL       654
#define TRAINER_LEOZAR         655
#define TRAINER_GLEIS_4        656
#define TRAINER_SPUTNOV_4      657
#define TRAINER_VLADOV_4       658
#define TRAINER_ADOLV_4        659
#define TRAINER_CHIEF          660
#define TRAINER_BRENDAN_9      661
#define TRAINER_PYRITE         662
#define TRAINER_BRENDAN_10     663
#define TRAINER_MAY_6          664
#define TRAINER_MAY_7          665
#define TRAINER_SENEX_2        666
#define TRAINER_BURNAGGIO      667
#define TRAINER_FROZONE        668
#define TRAINER_PARALISI       669
#define TRAINER_JOURDELAYS     670
#define TRAINER_MSDOLITTLE     671
#define TRAINER_ULTRAKICK      672
#define TRAINER_WAYNEFLETE     673
#define TRAINER_DYNAMO         674
#define TRAINER_ICIKLING       675
#define TRAINER_TRISHA         676
#define TRAINER_KENANDBEL      677
#define TRAINER_KIMANDIRIS     678
#define TRAINER_DOUBLEACT_3    679
#define TRAINER_JANANDJON      680
#define TRAINER_JOHNANDJAY_1   681
#define TRAINER_JOHNANDJAY_2   682
#define TRAINER_JOHNANDJAY_3   683
#define TRAINER_JOHNANDJAY_4   684
#define TRAINER_JOHNANDJAY_5   685
#define TRAINER_HANAANDMIKI    686
#define TRAINER_VENUSANDMILO   687
#define TRAINER_RITAANDSAM_1   688
#define TRAINER_RITAANDSAM_2   689
#define TRAINER_RITAANDSAM_3   690
#define TRAINER_RITAANDSAM_4   691
#define TRAINER_SIMONANDTABBY  692
#define TRAINER_EUGENE         693
