.macro @decap_ability_name, i, name
.org 0x81fa248 + i * 13
.area 13, 0x0
.string name
.endarea
.endmacro

@decap_ability_name 0, "-------"
@decap_ability_name 1, "Stench"
@decap_ability_name 2, "Drizzle"
@decap_ability_name 3, "Speed Boost"
@decap_ability_name 4, "Bulletproof"
@decap_ability_name 5, "Sturdy"
@decap_ability_name 6, "Damp"
@decap_ability_name 7, "Limber"
@decap_ability_name 8, "Sand Veil"
@decap_ability_name 9, "Static"
@decap_ability_name 10, "Volt Absorb"
@decap_ability_name 11, "Water Absorb"
@decap_ability_name 12, "Oblivious"
@decap_ability_name 13, "Cloud Nine"
@decap_ability_name 14, "Compoundeyes"
@decap_ability_name 15, "Insomnia"
@decap_ability_name 16, "Color Change"
@decap_ability_name 17, "Immunity"
@decap_ability_name 18, "Flash Fire"
@decap_ability_name 19, "Shield Dust"
@decap_ability_name 20, "Own Tempo"
@decap_ability_name 21, "Suction Cups"
@decap_ability_name 22, "Intimidate"
@decap_ability_name 23, "Shadow Tag"
@decap_ability_name 24, "Rough Skin"
@decap_ability_name 25, "Wonder Guard"
@decap_ability_name 26, "Levitate"
@decap_ability_name 27, "Effect Spore"
@decap_ability_name 28, "Synchronize"
@decap_ability_name 29, "Clear Body"
@decap_ability_name 30, "Natural Cure"
@decap_ability_name 31, "Lightningrod"
@decap_ability_name 32, "Serene Grace"
@decap_ability_name 33, "Swift Swim"
@decap_ability_name 34, "Chlorophyll"
@decap_ability_name 35, "Illuminate"
@decap_ability_name 36, "Trace"
@decap_ability_name 37, "Huge Power"
@decap_ability_name 38, "Poison Point"
@decap_ability_name 39, "Inner Focus"
@decap_ability_name 40, "Magma Armor"
@decap_ability_name 41, "Water Veil"
@decap_ability_name 42, "Magnet Pull"
@decap_ability_name 43, "Soundproof"
@decap_ability_name 44, "Aqua Heal"
@decap_ability_name 45, "Sand Stream"
@decap_ability_name 46, "Pressure"
@decap_ability_name 47, "Thick Fat"
@decap_ability_name 48, "Early Bird"
@decap_ability_name 49, "Flame Body"
@decap_ability_name 50, "Run Away"
@decap_ability_name 51, "Keen Eye"
@decap_ability_name 52, "Hyper Cutter"
@decap_ability_name 53, "Pickup"
@decap_ability_name 54, "Truant"
@decap_ability_name 55, "Hustle"
@decap_ability_name 56, "Cute Charm"
@decap_ability_name 57, "Plus"
@decap_ability_name 58, "Minus"
@decap_ability_name 59, "Forecast"
@decap_ability_name 60, "Sticky Hold"
@decap_ability_name 61, "Shed Skin"
@decap_ability_name 62, "Guts"
@decap_ability_name 63, "Marvel Scale"
@decap_ability_name 64, "Liquid Ooze"
@decap_ability_name 65, "Overgrow"
@decap_ability_name 66, "Blaze"
@decap_ability_name 67, "Torrent"
@decap_ability_name 68, "Swarm"
@decap_ability_name 69, "Rock Head"
@decap_ability_name 70, "Drought"
@decap_ability_name 71, "Arena Trap"
@decap_ability_name 72, "Vital Spirit"
@decap_ability_name 73, "White Smoke"
@decap_ability_name 74, "Pure Power"
@decap_ability_name 75, "Shell Armor"
@decap_ability_name 76, "Cacophony"
@decap_ability_name 77, "Air Lock"
