.macro @decap_ability_name, i, name
@decap_table 0x81fa248, 13, 13, i, name
.endmacro

@decap_ability_name ABILITY_NONE, "-------"
@decap_ability_name ABILITY_STENCH, "Stench"
@decap_ability_name ABILITY_DRIZZLE, "Drizzle"
@decap_ability_name ABILITY_SPEED_BOOST, "Speed Boost"
@decap_ability_name ABILITY_BATTLE_ARMOR, "Bulletproof"
@decap_ability_name ABILITY_STURDY, "Sturdy"
@decap_ability_name ABILITY_DAMP, "Damp"
@decap_ability_name ABILITY_LIMBER, "Limber"
@decap_ability_name ABILITY_SAND_VEIL, "Sand Veil"
@decap_ability_name ABILITY_STATIC, "Static"
@decap_ability_name ABILITY_VOLT_ABSORB, "Volt Absorb"
@decap_ability_name ABILITY_WATER_ABSORB, "Water Absorb"
@decap_ability_name ABILITY_OBLIVIOUS, "Oblivious"
@decap_ability_name ABILITY_CLOUD_NINE, "Cloud Nine"
@decap_ability_name ABILITY_COMPOUND_EYES, "CompoundEyes"
@decap_ability_name ABILITY_INSOMNIA, "Insomnia"
@decap_ability_name ABILITY_COLOR_CHANGE, "Color Change"
@decap_ability_name ABILITY_IMMUNITY, "Immunity"
@decap_ability_name ABILITY_FLASH_FIRE, "Flash Fire"
@decap_ability_name ABILITY_SHIELD_DUST, "Shield Dust"
@decap_ability_name ABILITY_OWN_TEMPO, "Own Tempo"
@decap_ability_name ABILITY_SUCTION_CUPS, "Suction Cups"
@decap_ability_name ABILITY_INTIMIDATE, "Intimidate"
@decap_ability_name ABILITY_SHADOW_TAG, "Shadow Tag"
@decap_ability_name ABILITY_ROUGH_SKIN, "Rough Skin"
@decap_ability_name ABILITY_WONDER_GUARD, "Wonder Guard"
@decap_ability_name ABILITY_LEVITATE, "Levitate"
@decap_ability_name ABILITY_EFFECT_SPORE, "Effect Spore"
@decap_ability_name ABILITY_SYNCHRONIZE, "Synchronize"
@decap_ability_name ABILITY_CLEAR_BODY, "Clear Body"
@decap_ability_name ABILITY_NATURAL_CURE, "Natural Cure"
@decap_ability_name ABILITY_LIGHTNING_ROD, "Lightningrod"
@decap_ability_name ABILITY_SERENE_GRACE, "Serene Grace"
@decap_ability_name ABILITY_SWIFT_SWIM, "Swift Swim"
@decap_ability_name ABILITY_CHLOROPHYLL, "Chlorophyll"
@decap_ability_name ABILITY_ILLUMINATE, "Illuminate"
@decap_ability_name ABILITY_TRACE, "Trace"
@decap_ability_name ABILITY_HUGE_POWER, "Huge Power"
@decap_ability_name ABILITY_POISON_POINT, "Poison Point"
@decap_ability_name ABILITY_INNER_FOCUS, "Inner Focus"
@decap_ability_name ABILITY_MAGMA_ARMOR, "Magma Armor"
@decap_ability_name ABILITY_WATER_VEIL, "Water Veil"
@decap_ability_name ABILITY_MAGNET_PULL, "Magnet Pull"
@decap_ability_name ABILITY_SOUNDPROOF, "Soundproof"
@decap_ability_name ABILITY_RAIN_DISH, "Aqua Heal"
@decap_ability_name ABILITY_SAND_STREAM, "Sand Stream"
@decap_ability_name ABILITY_PRESSURE, "Pressure"
@decap_ability_name ABILITY_THICK_FAT, "Thick Fat"
@decap_ability_name ABILITY_EARLY_BIRD, "Early Bird"
@decap_ability_name ABILITY_FLAME_BODY, "Flame Body"
@decap_ability_name ABILITY_RUN_AWAY, "Run Away"
@decap_ability_name ABILITY_KEEN_EYE, "Keen Eye"
@decap_ability_name ABILITY_HYPER_CUTTER, "Hyper Cutter"
@decap_ability_name ABILITY_PICKUP, "Pickup"
@decap_ability_name ABILITY_TRUANT, "Truant"
@decap_ability_name ABILITY_HUSTLE, "Hustle"
@decap_ability_name ABILITY_CUTE_CHARM, "Cute Charm"
@decap_ability_name ABILITY_PLUS, "Plus"
@decap_ability_name ABILITY_MINUS, "Minus"
@decap_ability_name ABILITY_FORECAST, "Forecast"
@decap_ability_name ABILITY_STICKY_HOLD, "Sticky Hold"
@decap_ability_name ABILITY_SHED_SKIN, "Shed Skin"
@decap_ability_name ABILITY_GUTS, "Guts"
@decap_ability_name ABILITY_MARVEL_SCALE, "Marvel Scale"
@decap_ability_name ABILITY_LIQUID_OOZE, "Liquid Ooze"
@decap_ability_name ABILITY_OVERGROW, "Overgrow"
@decap_ability_name ABILITY_BLAZE, "Blaze"
@decap_ability_name ABILITY_TORRENT, "Torrent"
@decap_ability_name ABILITY_SWARM, "Swarm"
@decap_ability_name ABILITY_ROCK_HEAD, "Rock Head"
@decap_ability_name ABILITY_DROUGHT, "Drought"
@decap_ability_name ABILITY_ARENA_TRAP, "Arena Trap"
@decap_ability_name ABILITY_VITAL_SPIRIT, "Vital Spirit"
@decap_ability_name ABILITY_WHITE_SMOKE, "White Smoke"
@decap_ability_name ABILITY_PURE_POWER, "Pure Power"
@decap_ability_name ABILITY_SHELL_ARMOR, "Shell Armor"
@decap_ability_name ABILITY_CACOPHONY, "Cacophony"
@decap_ability_name ABILITY_AIR_LOCK, "Air Lock"
