.macro @decap_item_name, i, name
.org 0x83c5564 + i * 44
.area 14, 0x0
.string name
.endarea
.endmacro

@decap_item_name ITEM_NONE, "????????"
@decap_item_name ITEM_AFRO_BALL, " Afro Ball"
@decap_item_name ITEM_ULTRA_BALL, "Ultra Ball"
@decap_item_name ITEM_GREAT_BALL, "Great Ball"
@decap_item_name ITEM_POKE_BALL, "Poké Ball"
@decap_item_name ITEM_NECRO_BALL, "Necro Ball"
@decap_item_name ITEM_NET_BALL, "Net Ball"
@decap_item_name ITEM_DIVE_BALL, "Dive Ball"
@decap_item_name ITEM_NEST_BALL, "Nest Ball"
@decap_item_name ITEM_REPEAT_BALL, "Repeat Ball"
@decap_item_name ITEM_TIMER_BALL, "Timer Ball"
@decap_item_name ITEM_LUXURY_BALL, "Luxury Ball"
@decap_item_name ITEM_ORPHEUS_BALL, "Orpheus Ball"
@decap_item_name ITEM_LIGHT_POTION, "Light Potion"
@decap_item_name ITEM_ANTIDOTE, "Antidote"
@decap_item_name ITEM_WATER_BOTTLE, "Water Bottle"
@decap_item_name ITEM_ANTIFREEZE, "Antifreeze"
@decap_item_name ITEM_AWAKENING, "Awakening"
@decap_item_name ITEM_PARALYZE_HEAL, "Parlyz Heal"
@decap_item_name ITEM_FULL_RESTORE, "Full Restore"
@decap_item_name ITEM_MAXI_POTION, "Maxi Potion"
@decap_item_name ITEM_HYPER_POTION, "Hyper Potion"
@decap_item_name ITEM_SUPER_POTION, "Super Potion"
@decap_item_name ITEM_SNAKE_OIL, "Snake Oil"
@decap_item_name ITEM_REVIVE, "Revive"
@decap_item_name ITEM_MAX_REVIVE, "Max Revive"
@decap_item_name ITEM_ZOMBIE_LIVER, "Zombie Liver"
@decap_item_name ITEM_SODA_POP, "Soda Pop"
@decap_item_name ITEM_LEMONADE, "Lemonade"
@decap_item_name ITEM_GATEAU, "Gateau     "
@decap_item_name ITEM_ENERGY_POWDER, "Energypowder"
@decap_item_name ITEM_ENERGY_ROOT, "Energy Root"
@decap_item_name ITEM_ACONITE_JUICE, "Aconite Juice"
@decap_item_name ITEM_ZOMBIE_CUKE, "Zombie Cuke"
@decap_item_name ITEM_ETHER, "Ether"
@decap_item_name ITEM_MAX_ETHER, "Max Ether"
@decap_item_name ITEM_ELIXIR, "Elixir"
@decap_item_name ITEM_MAX_ELIXIR, "Max Elixir"
@decap_item_name ITEM_CHIKUWA, "Chikuwa"
@decap_item_name ITEM_BLUE_FLUTE, "Blue Flute"
@decap_item_name ITEM_YELLOW_FLUTE, "Yellow Flute"
@decap_item_name ITEM_RED_FLUTE, "Red Flute"
@decap_item_name ITEM_BLACK_FLUTE, "Black Flute"
@decap_item_name ITEM_WHITE_FLUTE, "White Flute"
@decap_item_name ITEM_CHOC_ORANGE, "Choc Orange"
@decap_item_name ITEM_TURMURSPORE, "Turmurspore "
@decap_item_name ITEM_SHOAL_SALT, "Shoal Salt"
@decap_item_name ITEM_SHOAL_SHELL, "Shoal Shell"
@decap_item_name ITEM_HARDDISKSOLO, "HardDiskSolo"
@decap_item_name ITEM_BLUE_SHARD, "Blue Shard"
@decap_item_name ITEM_YELLOW_SHARD, "Yellow Shard"
@decap_item_name ITEM_GREEN_SHARD, "Green Shard"
@decap_item_name ITEM_034, "????????"
@decap_item_name ITEM_035, "????????"
@decap_item_name ITEM_036, "????????"
@decap_item_name ITEM_037, "????????"
@decap_item_name ITEM_038, "????????"
@decap_item_name ITEM_039, "????????"
@decap_item_name ITEM_03A, "????????"
@decap_item_name ITEM_03B, "????????"
@decap_item_name ITEM_03C, "????????"
@decap_item_name ITEM_03D, "????????"
@decap_item_name ITEM_03E, "????????"
@decap_item_name ITEM_WHITE_RABBIT, "White Rabbit"
@decap_item_name ITEM_RIESEN, "Riesen"
@decap_item_name ITEM_KINDER_EGG, "Kinder Egg"
@decap_item_name ITEM_MAGIC_STARS, "Magic Stars"
@decap_item_name ITEM_STARMIX, "Starmix"
@decap_item_name ITEM_RAGECANDYBAR, "RageCandyBar"
@decap_item_name ITEM_CARAMAC, "Caramac"
@decap_item_name ITEM_WINE_GUMS, "Wine Gums"
@decap_item_name ITEM_WAGON_WHEEL, "Wagon Wheel"
@decap_item_name ITEM_048, "????????"
@decap_item_name ITEM_REDUCT_REDUCE, "Reduct Reduce"
@decap_item_name ITEM_CRIT_PLUS, "Crit Plus"
@decap_item_name ITEM_ATTACK_PLUS, "Attack Plus"
@decap_item_name ITEM_DEFEND_PLUS, "Defend Plus"
@decap_item_name ITEM_SPEED_PLUS, "Speed Plus"
@decap_item_name ITEM_ACCURACY_PLUS, "Accuracy Plus"
@decap_item_name ITEM_SPECIAL_PLUS, "Special Plus"
@decap_item_name ITEM_POKE_DOLL, "Poké Doll"
@decap_item_name ITEM_FLUFFY_TAIL, "Fluffy Tail"
@decap_item_name ITEM_052, "????????"
@decap_item_name ITEM_SUPER_REPEL, "Super Repel"
@decap_item_name ITEM_MAX_REPEL, "Max Repel"
@decap_item_name ITEM_TELEPORTER, "Teleporter"
@decap_item_name ITEM_REPEL, "Repel"
@decap_item_name ITEM_057, "????????"
@decap_item_name ITEM_058, "????????"
@decap_item_name ITEM_059, "????????"
@decap_item_name ITEM_05A, "????????"
@decap_item_name ITEM_05B, "????????"
@decap_item_name ITEM_05C, "????????"
@decap_item_name ITEM_SUN_STONE, "Sun Stone"
@decap_item_name ITEM_MOON_STONE, "Moon Stone"
@decap_item_name ITEM_FIRE_STONE, "Fire Stone"
@decap_item_name ITEM_THUNDER_STONE, "Thunderstone"
@decap_item_name ITEM_WATER_STONE, "Water Stone"
@decap_item_name ITEM_LEAF_STONE, "Leaf Stone"
@decap_item_name ITEM_063, "????????"
@decap_item_name ITEM_064, "????????"
@decap_item_name ITEM_065, "????????"
@decap_item_name ITEM_066, "????????"
@decap_item_name ITEM_COLOGNE, "Cologne"
@decap_item_name ITEM_SPARK_TOKEN, "Spark Token"
@decap_item_name ITEM_069, "????????"
@decap_item_name ITEM_PEARL, "Pearl"
@decap_item_name ITEM_MUSH_MASK, "Mush Mask"
@decap_item_name ITEM_STARDUST, "Stardust"
@decap_item_name ITEM_STAR_PIECE, "Star Piece"
@decap_item_name ITEM_NUGGET, "Nugget"
@decap_item_name ITEM_BLUE_ROCK, "Blue Rock"
@decap_item_name ITEM_070, "????????"
@decap_item_name ITEM_071, "????????"
@decap_item_name ITEM_072, "????????"
@decap_item_name ITEM_073, "????????"
@decap_item_name ITEM_074, "????????"
@decap_item_name ITEM_075, "????????"
@decap_item_name ITEM_076, "????????"
@decap_item_name ITEM_077, "????????"
@decap_item_name ITEM_078, "????????"
@decap_item_name ITEM_ORANGE_MAIL, "Orange Mail"
@decap_item_name ITEM_HARBOR_MAIL, "Harbor Mail"
@decap_item_name ITEM_GLITTER_MAIL, "Glitter Mail"
@decap_item_name ITEM_MECH_MAIL, "Mech Mail"
@decap_item_name ITEM_WOOD_MAIL, "Wood Mail"
@decap_item_name ITEM_WAVE_MAIL, "Wave Mail"
@decap_item_name ITEM_BEAD_MAIL, "Bead Mail"
@decap_item_name ITEM_SHADOW_MAIL, "Shadow Mail"
@decap_item_name ITEM_TROPIC_MAIL, "Tropic Mail"
@decap_item_name ITEM_DREAM_MAIL, "Dream Mail"
@decap_item_name ITEM_FAB_MAIL, "Fab Mail"
@decap_item_name ITEM_RETRO_MAIL, "Retro Mail"
@decap_item_name ITEM_CHERI_BERRY, "Cheri Berry"
@decap_item_name ITEM_CHESTO_BERRY, "Chesto Berry"
@decap_item_name ITEM_PECHA_BERRY, "Pecha Berry"
@decap_item_name ITEM_RAWST_BERRY, "Rawst Berry"
@decap_item_name ITEM_ASPEAR_BERRY, "Aspear Berry"
@decap_item_name ITEM_LEPPA_BERRY, "Leppa Berry"
@decap_item_name ITEM_ORAN_BERRY, "Oran Berry"
@decap_item_name ITEM_PERSIM_BERRY, "Persim Berry"
@decap_item_name ITEM_LUM_BERRY, "Lum Berry"
@decap_item_name ITEM_SITRUS_BERRY, "Sitrus Berry"
@decap_item_name ITEM_FIGY_BERRY, "Figy Berry"
@decap_item_name ITEM_WIKI_BERRY, "Wiki Berry"
@decap_item_name ITEM_MAGO_BERRY, "Mago Berry"
@decap_item_name ITEM_AGUAV_BERRY, "Aguav Berry"
@decap_item_name ITEM_IAPAPA_BERRY, "Iapapa Berry"
@decap_item_name ITEM_RAZZ_BERRY, "Razz Berry"
@decap_item_name ITEM_BLUK_BERRY, "Bluk Berry"
@decap_item_name ITEM_NANAB_BERRY, "Nanab Berry"
@decap_item_name ITEM_WEPEAR_BERRY, "Wepear Berry"
@decap_item_name ITEM_PINAP_BERRY, "Pinap Berry"
@decap_item_name ITEM_POMEG_BERRY, "Pomeg Berry"
@decap_item_name ITEM_KELPSY_BERRY, "Kelpsy Berry"
@decap_item_name ITEM_QUALOT_BERRY, "Qualot Berry"
@decap_item_name ITEM_HONDEW_BERRY, "Hondew Berry"
@decap_item_name ITEM_GREPA_BERRY, "Grepa Berry"
@decap_item_name ITEM_TAMATO_BERRY, "Tamato Berry"
@decap_item_name ITEM_CORNN_BERRY, "Cornn Berry"
@decap_item_name ITEM_MAGOST_BERRY, "Magost Berry"
@decap_item_name ITEM_RABUTA_BERRY, "Rabuta Berry"
@decap_item_name ITEM_NOMEL_BERRY, "Nomel Berry"
@decap_item_name ITEM_SPELON_BERRY, "Spelon Berry"
@decap_item_name ITEM_PAMTRE_BERRY, "Pamtre Berry"
@decap_item_name ITEM_WATMEL_BERRY, "Watmel Berry"
@decap_item_name ITEM_DURIN_BERRY, "Durin Berry"
@decap_item_name ITEM_BELUE_BERRY, "Belue Berry"
@decap_item_name ITEM_LIECHI_BERRY, "Liechi Berry"
@decap_item_name ITEM_GANLON_BERRY, "Ganlon Berry"
@decap_item_name ITEM_SALAC_BERRY, "Salac Berry"
@decap_item_name ITEM_PETAYA_BERRY, "Petaya Berry"
@decap_item_name ITEM_APICOT_BERRY, "Apicot Berry"
@decap_item_name ITEM_LANSAT_BERRY, "Lansat Berry"
@decap_item_name ITEM_STARF_BERRY, "Starf Berry"
@decap_item_name ITEM_ENIGMA_BERRY, "Enigma Berry"
@decap_item_name ITEM_0B0, "????????"
@decap_item_name ITEM_0B1, "????????"
@decap_item_name ITEM_0B2, "????????"
@decap_item_name ITEM_YOUYOUYOU, "Youyouyou!"
@decap_item_name ITEM_GLOW_HERB, "Glow Herb"
@decap_item_name ITEM_DUMBBELLS, "Dumbbells "
@decap_item_name ITEM_BRAIN_LINK, "Brain Link"
@decap_item_name ITEM_DEMON_HORN, "Demon Horn"
@decap_item_name ITEM_KILIN_HORN, "Kilin Horn "
@decap_item_name ITEM_LOVESLAYER, "Loveslayer"
@decap_item_name ITEM_POWER_HAT, "Power Hat "
@decap_item_name ITEM_SOME_TEETH, "Some Teeth"
@decap_item_name ITEM_FLASH_SCALES, "Flash Scales"
@decap_item_name ITEM_GAMBLE_FISH, "Gamble Fish"
@decap_item_name ITEM_DISPELL_TOKEN, "Dispell Toke"
@decap_item_name ITEM_TAIJI_DUST, "Taiji Dust"
@decap_item_name ITEM_DEEP_SEA_TOOTH, "Deepseatooth"
@decap_item_name ITEM_DEEP_SEA_SCALE, "Deepseascale"
@decap_item_name ITEM_VOODOO_CANDY, "Voodoo Candy"
@decap_item_name ITEM_NEVERSTONE, "Neverstone"
@decap_item_name ITEM_CHAOS_OF_ODEN, "Chaos Of Oden"
@decap_item_name ITEM_LOVE_DRAIN, "Love Drain"
@decap_item_name ITEM_SNIPE_SCOPE, "Snipe Scope"
@decap_item_name ITEM_EXCALIBUR, "Excalibur"
@decap_item_name ITEM_LEFTOVERS, "Leftovers"
@decap_item_name ITEM_RED_STEW, "Red Stew"
@decap_item_name ITEM_MINER_TM, "Miner TM"
@decap_item_name ITEM_VOLCANO_POT, "Volcano Pot"
@decap_item_name ITEM_OLD_BRICK, "Old Brick"
@decap_item_name ITEM_WONDERPLUM, "Wonderplum"
@decap_item_name ITEM_BASS_GUITAR, "Bass Guitar"
@decap_item_name ITEM_SPIKED_GLOVE, "Spiked Glove"
@decap_item_name ITEM_ELECTRICHONEY, "Electrichoney"
@decap_item_name ITEM_GODS_TEAR, "God's Tear"
@decap_item_name ITEM_ANADRIN_TALON, "Anadrin Talon"
@decap_item_name ITEM_SNAKE_EYES, "Snake Eyes"
@decap_item_name ITEM_RAINBOWFROST, "Rainbowfrost"
@decap_item_name ITEM_CURSED_SKULL, "Curséd Skull"
@decap_item_name ITEM_MEWTWO_BRAIN, "Mewtwo Brain"
@decap_item_name ITEM_CINNAMON, "Cinnamon"
@decap_item_name ITEM_TREASURE_BALL, "Treasure Ball"
@decap_item_name ITEM_PLUS_BAND, "Plus Band "
@decap_item_name ITEM_MINER_DOLL, "Miner Doll"
@decap_item_name ITEM_MEATY_BELL, "Meaty Bell"
@decap_item_name ITEM_SOMA, "Soma"
@decap_item_name ITEM_SAND_CLOAK, "Sand Cloak"
@decap_item_name ITEM_POKEPHONE, "PokéPhone "
@decap_item_name ITEM_GASEOUS_ZINC, "Gaseous Zinc"
@decap_item_name ITEM_POKEGEAR, "Pokégear"
@decap_item_name ITEM_PACHI_SWORD, "Pachi Sword"
@decap_item_name ITEM_STATS_VIEWER, "????????"
@decap_item_name ITEM_0E3, "????????"
@decap_item_name ITEM_0E4, "????????"
@decap_item_name ITEM_0E5, "????????"
@decap_item_name ITEM_0E6, "????????"
@decap_item_name ITEM_0E7, "????????"
@decap_item_name ITEM_0E8, "????????"
@decap_item_name ITEM_0E9, "????????"
@decap_item_name ITEM_0EA, "????????"
@decap_item_name ITEM_0EB, "????????"
@decap_item_name ITEM_0EC, "????????"
@decap_item_name ITEM_0ED, "????????"
@decap_item_name ITEM_0EE, "????????"
@decap_item_name ITEM_0EF, "????????"
@decap_item_name ITEM_0F0, "????????"
@decap_item_name ITEM_0F1, "????????"
@decap_item_name ITEM_0F2, "????????"
@decap_item_name ITEM_0F3, "????????"
@decap_item_name ITEM_0F4, "????????"
@decap_item_name ITEM_0F5, "????????"
@decap_item_name ITEM_0F6, "????????"
@decap_item_name ITEM_0F7, "????????"
@decap_item_name ITEM_0F8, "????????"
@decap_item_name ITEM_0F9, "????????"
@decap_item_name ITEM_SECRET_KEY, "Secret Key"
@decap_item_name ITEM_HIDDEN_KEY, "Hidden Key"
@decap_item_name ITEM_ARCANE_KEY, "Arcane Key"
@decap_item_name ITEM_ABSTRUSE_KEY, "Abstruse Key"
@decap_item_name ITEM_RED_SCARF, "Red Scarf"
@decap_item_name ITEM_BLUE_SCARF, "Blue Scarf"
@decap_item_name ITEM_PINK_SCARF, "Pink Scarf"
@decap_item_name ITEM_GREEN_SCARF, "Green Scarf"
@decap_item_name ITEM_YELLOW_SCARF, "Yellow Scarf"
@decap_item_name ITEM_YELLOW_VESPA, "Yellow Vespa"
@decap_item_name ITEM_COIN_CASE, "Coin Case"
@decap_item_name ITEM_ITEMFINDER, "Itemfinder"
@decap_item_name ITEM_OLD_ROD, "Old Rod"
@decap_item_name ITEM_CURSED_ROD, "Cursed Rod"
@decap_item_name ITEM_KINGDRA_ROD, "Kingdra Rod"
@decap_item_name ITEM_SS_TICKET, "S.s. Ticket"
@decap_item_name ITEM_CATS_EYE, "Cat's Eye"
@decap_item_name ITEM_10B, "????????"
@decap_item_name ITEM_WAILMER_PAIL, "Wailmer Pail"
@decap_item_name ITEM_SPANNER, "Spanner   "
@decap_item_name ITEM_BONE_KEYRING, "Bone Keyring"
@decap_item_name ITEM_BROKEN_HEART, "Broken Heart"
@decap_item_name ITEM_AIR_TREKS, "Air Treks"
@decap_item_name ITEM_POKEBLOCK_CASE, " Case"
@decap_item_name ITEM_GYM_TICKETS, "Gym Tickets"
@decap_item_name ITEM_SPATIAL_PASS, "Spatial Pass"
@decap_item_name ITEM_BLUE_FISH, "Blue Fish"
@decap_item_name ITEM_PINK_INK, "Pink Ink"
@decap_item_name ITEM_ODD_KEYSTONE, "Odd Keystone"
@decap_item_name ITEM_HAJIKE_BIRD, "Hajike Bird"
@decap_item_name ITEM_RYDRAKE_WING, "Rydrake Wing"
@decap_item_name ITEM_SCRATCHKITTEN, "Scratchkitten"
@decap_item_name ITEM_THUNDER_CUB, "Thunder Cub"
@decap_item_name ITEM_SCRUFFY_CHICK, "Scruffy Chick"
@decap_item_name ITEM_FLASH_PUPPY, "Flash Puppy"
@decap_item_name ITEM_SPARKLY_PONY, "Sparkly Pony"
@decap_item_name ITEM_VISITORS_PASS, "Visitors Pass"
@decap_item_name ITEM_DRAGON_EGG, "Dragon Egg"
@decap_item_name ITEM_ASTRAL_LENS, "Astral Lens"
@decap_item_name ITEM_TM01_FOCUS_PUNCH, "TM01"
@decap_item_name ITEM_TM02_DRAGON_CLAW, "TM02"
@decap_item_name ITEM_TM03_WATER_PULSE, "TM03"
@decap_item_name ITEM_TM04_CALM_MIND, "TM04"
@decap_item_name ITEM_TM05_ROAR, "TM05"
@decap_item_name ITEM_TM06_TOXIC, "TM06"
@decap_item_name ITEM_TM07_HAIL, "TM07"
@decap_item_name ITEM_TM08_BULK_UP, "TM08"
@decap_item_name ITEM_TM09_GRASSWHISTLE, "TM09"
@decap_item_name ITEM_TM10_HIDDEN_POWER, "TM10"
@decap_item_name ITEM_TM11_SUNNY_DAY, "TM11"
@decap_item_name ITEM_TM12_TAUNT, "TM12"
@decap_item_name ITEM_TM13_ICE_BEAM, "TM13"
@decap_item_name ITEM_TM14_BLIZZARD, "TM14"
@decap_item_name ITEM_TM15_HYPER_BEAM, "TM15"
@decap_item_name ITEM_TM16_LIGHT_SCREEN, "TM16"
@decap_item_name ITEM_TM17_PROTECT, "TM17"
@decap_item_name ITEM_TM18_RAIN_DANCE, "TM18"
@decap_item_name ITEM_TM19_GIGA_DRAIN, "TM19"
@decap_item_name ITEM_TM20_SAFEGUARD, "TM20"
@decap_item_name ITEM_TM21_FRUSTRATION, "TM21"
@decap_item_name ITEM_TM22_SOLARBEAM, "TM22"
@decap_item_name ITEM_TM23_IRON_SLAM, "TM23"
@decap_item_name ITEM_TM24_THUNDERBOLT, "TM24"
@decap_item_name ITEM_TM25_THUNDER, "TM25"
@decap_item_name ITEM_TM26_EARTHQUAKE, "TM26"
@decap_item_name ITEM_TM27_RETURN, "TM27"
@decap_item_name ITEM_TM28_DIG, "TM28"
@decap_item_name ITEM_TM29_PSYCHIC, "TM29"
@decap_item_name ITEM_TM30_SHADOW_BALL, "TM30"
@decap_item_name ITEM_TM31_ICE_PUNCH, "TM31"
@decap_item_name ITEM_TM32_DOUBLE_TEAM, "TM32"
@decap_item_name ITEM_TM33_REFLECT, "TM33"
@decap_item_name ITEM_TM34_SHOCK_WAVE, "TM34"
@decap_item_name ITEM_TM35_FIRE_PUMP, "TM35"
@decap_item_name ITEM_TM36_SLUDGE_BOMB, "TM36"
@decap_item_name ITEM_TM37_SANDSTORM, "TM37"
@decap_item_name ITEM_TM38_FIRE_BLAST, "TM38"
@decap_item_name ITEM_TM39_ROCK_TOMB, "TM39"
@decap_item_name ITEM_TM40_BEAT_UP, "TM40"
@decap_item_name ITEM_TM41_TORMENT, "TM41"
@decap_item_name ITEM_TM42_FACADE, "TM42"
@decap_item_name ITEM_TM43_SECRET_POWER, "TM43"
@decap_item_name ITEM_TM44_REST, "TM44"
@decap_item_name ITEM_TM45_ATTRACT, "TM45"
@decap_item_name ITEM_TM46_THIEF, "TM46"
@decap_item_name ITEM_TM47_STEEL_WING, "TM47"
@decap_item_name ITEM_TM48_SKILL_SWAP, "TM48"
@decap_item_name ITEM_TM49_SNATCH, "TM49"
@decap_item_name ITEM_TM50_OVERHEAT, "TM50"
@decap_item_name ITEM_HM01_CUT, "HM01"
@decap_item_name ITEM_HM02_FLY, "HM02"
@decap_item_name ITEM_HM03_SURF, "HM03"
@decap_item_name ITEM_HM04_STRENGTH, "HM04"
@decap_item_name ITEM_HM05_FLASH, "HM05"
@decap_item_name ITEM_HM06_ROCK_SMASH, "HM06"
@decap_item_name ITEM_HM07_WATERFALL, "HM07"
@decap_item_name ITEM_HM08_DIVE, "HM08"
@decap_item_name ITEM_15B, "????????"
@decap_item_name ITEM_15C, "????????"