.macro @decap_item_desc, i, offset, desc
.org offset
.string desc
.endmacro

@decap_item_desc ITEM_NONE, 0x83c5562, ""
@decap_item_desc ITEM_AFRO_BALL, 0x83c2028, "The 100% catch   \nball made by the\nDeadly Seven."
@decap_item_desc ITEM_ULTRA_BALL, 0x83c205b, "A better Ball with\na higher catch rate\nthan a Great Ball."
@decap_item_desc ITEM_GREAT_BALL, 0x83c2095, "A good Ball with a\nhigher catch rate\nthan a Poké Ball."
@decap_item_desc ITEM_POKE_BALL, 0x83c20cc, "A tool used for\ncatching wild\nPokémon."
@decap_item_desc ITEM_NECRO_BALL, 0x83c20f3, "An ancient Ball\nforged in hellfire 1000\nyears ago.  "
@decap_item_desc ITEM_NET_BALL, 0x83c2128, "A Ball that works\nwell on Water- and\nBug-type Pokémon."
@decap_item_desc ITEM_DIVE_BALL, 0x83c215f, "A Ball that works\nbetter on Pokémon\non the ocean floor."
@decap_item_desc ITEM_NEST_BALL, 0x83c2197, "A Ball that works\nbetter on weaker\nPokémon."
@decap_item_desc ITEM_REPEAT_BALL, 0x83c21c3, "A Ball that works\nbetter on Pokémon\ncaught before."
@decap_item_desc ITEM_TIMER_BALL, 0x83c21f6, "More effective as\nmore turns are\ntaken in battle."
@decap_item_desc ITEM_LUXURY_BALL, 0x83c2228, "A cozy Ball that\nmakes Pokémon\nmore friendly."
@decap_item_desc ITEM_ORPHEUS_BALL, 0x83c2256, "A rare Ball made\nto commemorate a\nconcert.      "
@decap_item_desc ITEM_LIGHT_POTION, 0x83c2287, "Restores the HP of\na Pokémon by\n20 points."
@decap_item_desc ITEM_ANTIDOTE, 0x83c22b2, "Heals a poisoned\nPokémon."
@decap_item_desc ITEM_WATER_BOTTLE, 0x83c22cc, "Heals Pokémon\nof a burn."
@decap_item_desc ITEM_ANTIFREEZE, 0x83c22e5, "Defrosts a frozen\nPokémon."
@decap_item_desc ITEM_AWAKENING, 0x83c2300, "Awakens a sleeping\nPokémon."
@decap_item_desc ITEM_PARALYZE_HEAL, 0x83c231c, "Heals a paralyzed\nPokémon."
@decap_item_desc ITEM_FULL_RESTORE, 0x83c2337, "Fully restores the\nHP and status of a\nPokémon."
@decap_item_desc ITEM_MAXI_POTION, 0x83c2366, "Fully restores the\nHP of a Pokémon."
@decap_item_desc ITEM_HYPER_POTION, 0x83c238a, "Restores the HP of\na Pokémon by\n200 points."
@decap_item_desc ITEM_SUPER_POTION, 0x83c23b6, "Restores the HP of\na Pokémon by\n50 points."
@decap_item_desc ITEM_SNAKE_OIL, 0x83c23e1, "Heals all status\nproblems. Maybe.\nBelieve me?"
@decap_item_desc ITEM_REVIVE, 0x83c240f, "Revives a fainted\nPokémon with half\nits HP."
@decap_item_desc ITEM_MAX_REVIVE, 0x83c243b, "Revives a fainted\nPokémon with all\nits HP."
@decap_item_desc ITEM_ZOMBIE_LIVER, 0x83c2466, "An undead liver\nthat heals HP\nby 50 points.   "
@decap_item_desc ITEM_SODA_POP, 0x83c2495, "A fizzy soda drink\nthat restores HP\nby 60 points."
@decap_item_desc ITEM_LEMONADE, 0x83c24c7, "A very sweet drink\nthat restores HP\nby 80 points."
@decap_item_desc ITEM_GATEAU, 0x83c24f9, "The Black Forest\nkind. Restores\n100 HP if eaten. "
@decap_item_desc ITEM_ENERGY_POWDER, 0x83c252b, "A bitter powder\nthat restores HP\nby 50 points."
@decap_item_desc ITEM_ENERGY_ROOT, 0x83c255a, "A bitter root\nthat restores HP\nby 200 points."
@decap_item_desc ITEM_ACONITE_JUICE, 0x83c2588, "A bitter juice \nthat heals all\nstatus problems."
@decap_item_desc ITEM_ZOMBIE_CUKE, 0x83c25b8, "A toxic plant     \nthat revives a\nfainted Pokémon."
@decap_item_desc ITEM_ETHER, 0x83c25eb, "Restores the PP\nof a selected move\nby 10."
@decap_item_desc ITEM_MAX_ETHER, 0x83c2615, "Fully restores the\nPP of a selected\nmove."
@decap_item_desc ITEM_ELIXIR, 0x83c263f, "Restores the PP\nof all moves by 10."
@decap_item_desc ITEM_MAX_ELIXIR, 0x83c2663, "Fully restores the\nPP of a Pokémon's\nmoves."
@decap_item_desc ITEM_CHIKUWA, 0x83c268f, "A tubular snack\nthat heals all status\nproblems.  "
@decap_item_desc ITEM_BLUE_FLUTE, 0x83c26c1, "A glass flute that\nawakens sleeping\nPokémon."
@decap_item_desc ITEM_YELLOW_FLUTE, 0x83c26ee, "A glass flute that\nsnaps Pokémon\nout of confusion."
@decap_item_desc ITEM_RED_FLUTE, 0x83c2721, "A glass flute that\nsnaps Pokémon\nout of attraction."
@decap_item_desc ITEM_BLACK_FLUTE, 0x83c2755, "A glass flute that\nkeeps away wild\nPokémon."
@decap_item_desc ITEM_WHITE_FLUTE, 0x83c2781, "A glass flute that\nlures wild Pokémon."
@decap_item_desc ITEM_CHOC_ORANGE, 0x83c27a8, "Tasty chocolate\norange that heals\n 20 points.   "
@decap_item_desc ITEM_TURMURSPORE, 0x83c27d9, "Fully revives and\nrestores all\nfainted Pokémon."
@decap_item_desc ITEM_SHOAL_SALT, 0x83c2809, "Salt obtained from\ndeep inside the\nShoal Cave."
@decap_item_desc ITEM_SHOAL_SHELL, 0x83c2838, "A seashell found\ndeep inside the\nShoal Cave."
@decap_item_desc ITEM_HARDDISKSOLO, 0x83c2865, "An ancient single by\nOrifice of Nefarious\nPurpose."
@decap_item_desc ITEM_BLUE_SHARD, 0x83c2898, "A shard from an\nancient item.\nCan be sold cheaply."
@decap_item_desc ITEM_YELLOW_SHARD, 0x83c28cb, "A shard from an\nancient item.\nCan be sold cheaply."
@decap_item_desc ITEM_GREEN_SHARD, 0x83c28fe, "A shard from an\nancient item.\nCan be sold cheaply."
@decap_item_desc ITEM_034, 0x83c5562, ""
@decap_item_desc ITEM_035, 0x83c5562, ""
@decap_item_desc ITEM_036, 0x83c5562, ""
@decap_item_desc ITEM_037, 0x83c5562, ""
@decap_item_desc ITEM_038, 0x83c5562, ""
@decap_item_desc ITEM_039, 0x83c5562, ""
@decap_item_desc ITEM_03A, 0x83c5562, ""
@decap_item_desc ITEM_03B, 0x83c5562, ""
@decap_item_desc ITEM_03C, 0x83c5562, ""
@decap_item_desc ITEM_03D, 0x83c5562, ""
@decap_item_desc ITEM_03E, 0x83c5562, ""
@decap_item_desc ITEM_WHITE_RABBIT, 0x83c2931, "Chewy milk sweet\nRaises HP.  "
@decap_item_desc ITEM_RIESEN, 0x83c294f, "A manly sweet.\nRaises Attack\nof Pokés."
@decap_item_desc ITEM_KINDER_EGG, 0x83c2976, "Sweet that\nguards a toy.\nRaises Def. \n"
@decap_item_desc ITEM_MAGIC_STARS, 0x83c299e, "Chocolate stars\nwith faces. Raise\nSpd"
@decap_item_desc ITEM_STARMIX, 0x83c29c4, "Zany sweets.\nTogether, raise\nSp. Atk.  "
@decap_item_desc ITEM_RAGECANDYBAR, 0x83c29ec, "Raises the level\nof a Pokémon by\none."
@decap_item_desc ITEM_CARAMAC, 0x83c2a12, "Thin chocolate bar.\nRaises one move's\nPP."
@decap_item_desc ITEM_WINE_GUMS, 0x83c2a3c, "Themed sweets.\nEat to raise \nSp. Def.  "
@decap_item_desc ITEM_WAGON_WHEEL, 0x83c2a64, "Biscuits with mallow\nand coating. Max\nout PP. "
@decap_item_desc ITEM_048, 0x83c5562, ""
@decap_item_desc ITEM_REDUCT_REDUCE, 0x83c2a93, "Prevents stat\nreduction when\nused in battle."
@decap_item_desc ITEM_CRIT_PLUS, 0x83c2ac0, "Raises the\ncritical-hit ratio\nduring one battle."
@decap_item_desc ITEM_ATTACK_PLUS, 0x83c2af1, "Raises the stat\nAttack during one\nbattle."
@decap_item_desc ITEM_DEFEND_PLUS, 0x83c2b1b, "Raises the stat\nDefense during one\nbattle."
@decap_item_desc ITEM_SPEED_PLUS, 0x83c2b46, "Raises the stat\nSpeed during one\nbattle."
@decap_item_desc ITEM_ACCURACY_PLUS, 0x83c2b6f, "Raises accuracy\nof attack moves\nduring one battle."
@decap_item_desc ITEM_SPECIAL_PLUS, 0x83c2ba2, "Raises the stat\nSp. Atk during one\nbattle."
@decap_item_desc ITEM_POKE_DOLL, 0x83c2bcd, "Use to flee from\nany battle with\na wild Pokémon."
@decap_item_desc ITEM_FLUFFY_TAIL, 0x83c2bfe, "Use to flee from\nany battle with\na wild Pokémon."
@decap_item_desc ITEM_052, 0x83c5562, ""
@decap_item_desc ITEM_SUPER_REPEL, 0x83c2c2f, "Repels weak wild\nPokémon for 200\nsteps."
@decap_item_desc ITEM_MAX_REPEL, 0x83c2c57, "Repels weak wild\nPokémon for 250\nsteps."
@decap_item_desc ITEM_TELEPORTER, 0x83c2c7f, "Use to escape\ninstantly from a\ncave or a dungeon."
@decap_item_desc ITEM_REPEL, 0x83c2cb1, "Repels weak wild\nPokémon for 100\nsteps."
@decap_item_desc ITEM_057, 0x83c5562, ""
@decap_item_desc ITEM_058, 0x83c5562, ""
@decap_item_desc ITEM_059, 0x83c5562, ""
@decap_item_desc ITEM_05A, 0x83c5562, ""
@decap_item_desc ITEM_05B, 0x83c5562, ""
@decap_item_desc ITEM_05C, 0x83c5562, ""
@decap_item_desc ITEM_SUN_STONE, 0x83c2cd9, "Makes certain\nspecies of Pokémon\nevolve."
@decap_item_desc ITEM_MOON_STONE, 0x83c2d02, "Makes certain\nspecies of Pokémon\nevolve."
@decap_item_desc ITEM_FIRE_STONE, 0x83c2d2b, "Makes certain\nspecies of Pokémon\nevolve."
@decap_item_desc ITEM_THUNDER_STONE, 0x83c2d54, "Makes certain\nspecies of Pokémon\nevolve."
@decap_item_desc ITEM_WATER_STONE, 0x83c2d7d, "Makes certain\nspecies of Pokémon\nevolve."
@decap_item_desc ITEM_LEAF_STONE, 0x83c2da6, "Makes certain\nspecies of Pokémon\nevolve."
@decap_item_desc ITEM_063, 0x83c5562, ""
@decap_item_desc ITEM_064, 0x83c5562, ""
@decap_item_desc ITEM_065, 0x83c5562, ""
@decap_item_desc ITEM_066, 0x83c5562, ""
@decap_item_desc ITEM_COLOGNE, 0x83c2dcf, "Expensive,\nnutritious cologne.\nTasty, too."
@decap_item_desc ITEM_SPARK_TOKEN, 0x83c2e00, "A token for a\nvery special \npet from the Count."
@decap_item_desc ITEM_069, 0x83c5562, ""
@decap_item_desc ITEM_PEARL, 0x83c2e31, "A pretty pearl.\nCan be sold cheaply."
@decap_item_desc ITEM_MUSH_MASK, 0x83c2e56, "A mask of a \nmushroom head. "
@decap_item_desc ITEM_STARDUST, 0x83c2e8c, "Beautiful red sand.\nCan be sold at a\nhigh price."
@decap_item_desc ITEM_STAR_PIECE, 0x83c2ebd, "A red gem shard.\nIt would sell for a\nvery high price."
@decap_item_desc ITEM_NUGGET, 0x83c2ef3, "A nugget of pure\ngold. Can be sold at\na high price."
@decap_item_desc ITEM_BLUE_ROCK, 0x83c2f27, "A pretty blue\nrock. Magenpies\nlove it.      "
@decap_item_desc ITEM_070, 0x83c5562, ""
@decap_item_desc ITEM_071, 0x83c5562, ""
@decap_item_desc ITEM_072, 0x83c5562, ""
@decap_item_desc ITEM_073, 0x83c5562, ""
@decap_item_desc ITEM_074, 0x83c5562, ""
@decap_item_desc ITEM_075, 0x83c5562, ""
@decap_item_desc ITEM_076, 0x83c5562, ""
@decap_item_desc ITEM_077, 0x83c5562, ""
@decap_item_desc ITEM_078, 0x83c5562, ""
@decap_item_desc ITEM_ORANGE_MAIL, 0x83c2f54, "A Zigzagoon-print\nMail to be held by\na Pokémon."
@decap_item_desc ITEM_HARBOR_MAIL, 0x83c2f84, "A Wingull-print\nMail to be held by\na Pokémon."
@decap_item_desc ITEM_GLITTER_MAIL, 0x83c2fb2, "A Pikachu-print\nMail to be held by\na Pokémon."
@decap_item_desc ITEM_MECH_MAIL, 0x83c2fe0, "A Magnemite-print\nMail to be held by\na Pokémon."
@decap_item_desc ITEM_WOOD_MAIL, 0x83c3010, "A Slakoth-print\nMail to be held by\na Pokémon."
@decap_item_desc ITEM_WAVE_MAIL, 0x83c303e, "A Wailmer-print\nMail to be held by\na Pokémon."
@decap_item_desc ITEM_BEAD_MAIL, 0x83c306c, "Mail featuring a\nsketch of the\nholding Pokémon."
@decap_item_desc ITEM_SHADOW_MAIL, 0x83c309c, "A Duskull-print\nMail to be held by\na Pokémon."
@decap_item_desc ITEM_TROPIC_MAIL, 0x83c30ca, "A Bellossom-print\nMail to be held by\na Pokémon."
@decap_item_desc ITEM_DREAM_MAIL, 0x83c30fa, "Mail featuring a\nsketch of the\nholding Pokémon."
@decap_item_desc ITEM_FAB_MAIL, 0x83c312a, "A gorgeous-print\nMail to be held\nby a Pokémon."
@decap_item_desc ITEM_RETRO_MAIL, 0x83c3159, "Mail featuring the\ndrawings of three\nPokémon."
@decap_item_desc ITEM_CHERI_BERRY, 0x83c3187, "A hold item that\nheals paralysis\nin battle."
@decap_item_desc ITEM_CHESTO_BERRY, 0x83c31b3, "A hold item that\nawakens Pokémon\nin battle."
@decap_item_desc ITEM_PECHA_BERRY, 0x83c31df, "A hold item that\nheals poisoning\nin battle."
@decap_item_desc ITEM_RAWST_BERRY, 0x83c320b, "A hold item that\nheals a burn in\nbattle."
@decap_item_desc ITEM_ASPEAR_BERRY, 0x83c3234, "A hold item that\ndefrosts Pokémon\nin battle."
@decap_item_desc ITEM_LEPPA_BERRY, 0x83c3261, "A hold item that\nrestores 10 PP in\nbattle."
@decap_item_desc ITEM_ORAN_BERRY, 0x83c328c, "A hold item that\nrestores 10 HP in\nbattle."
@decap_item_desc ITEM_PERSIM_BERRY, 0x83c32b7, "A hold item that\nheals confusion\nin battle."
@decap_item_desc ITEM_LUM_BERRY, 0x83c32e3, "A hold item that\nheals status in\nbattle."
@decap_item_desc ITEM_SITRUS_BERRY, 0x83c330c, "A hold item that\nrestores 30 HP in\nbattle."
@decap_item_desc ITEM_FIGY_BERRY, 0x83c3337, "A hold item that\nrestores HP but\nmay confuse."
@decap_item_desc ITEM_WIKI_BERRY, 0x83c3365, "A hold item that\nrestores HP but\nmay confuse."
@decap_item_desc ITEM_MAGO_BERRY, 0x83c3393, "A hold item that\nrestores HP but\nmay confuse."
@decap_item_desc ITEM_AGUAV_BERRY, 0x83c33c1, "A hold item that\nrestores HP but\nmay confuse."
@decap_item_desc ITEM_IAPAPA_BERRY, 0x83c33ef, "A hold item that\nrestores HP but\nmay confuse."
@decap_item_desc ITEM_RAZZ_BERRY, 0x83c341d, " ingredient.\nPlant in loamy soil\nto grow Razz."
@decap_item_desc ITEM_BLUK_BERRY, 0x83c3451, " ingredient.\nPlant in loamy soil\nto grow Bluk."
@decap_item_desc ITEM_NANAB_BERRY, 0x83c3485, " ingredient.\nPlant in loamy soil\nto grow Nanab."
@decap_item_desc ITEM_WEPEAR_BERRY, 0x83c34ba, " ingredient.\nPlant in loamy soil\nto grow Wepear."
@decap_item_desc ITEM_PINAP_BERRY, 0x83c34f0, " ingredient.\nPlant in loamy soil\nto grow Pinap."
@decap_item_desc ITEM_POMEG_BERRY, 0x83c3525, " ingredient.\nPlant in loamy soil\nto grow Pomeg."
@decap_item_desc ITEM_KELPSY_BERRY, 0x83c355a, " ingredient.\nPlant in loamy soil\nto grow Kelpsy."
@decap_item_desc ITEM_QUALOT_BERRY, 0x83c3590, " ingredient.\nPlant in loamy soil\nto grow Qualot."
@decap_item_desc ITEM_HONDEW_BERRY, 0x83c35c6, " ingredient.\nPlant in loamy soil\nto grow Hondew."
@decap_item_desc ITEM_GREPA_BERRY, 0x83c35fc, " ingredient.\nPlant in loamy soil\nto grow Grepa."
@decap_item_desc ITEM_TAMATO_BERRY, 0x83c3631, " ingredient.\nPlant in loamy soil\nto grow Tamato."
@decap_item_desc ITEM_CORNN_BERRY, 0x83c3667, " ingredient.\nPlant in loamy soil\nto grow Cornn."
@decap_item_desc ITEM_MAGOST_BERRY, 0x83c369c, " ingredient.\nPlant in loamy soil\nto grow Magost."
@decap_item_desc ITEM_RABUTA_BERRY, 0x83c36d2, " ingredient.\nPlant in loamy soil\nto grow Rabuta."
@decap_item_desc ITEM_NOMEL_BERRY, 0x83c3708, " ingredient.\nPlant in loamy soil\nto grow Nomel."
@decap_item_desc ITEM_SPELON_BERRY, 0x83c373d, " ingredient.\nPlant in loamy soil\nto grow Spelon."
@decap_item_desc ITEM_PAMTRE_BERRY, 0x83c3773, " ingredient.\nPlant in loamy soil\nto grow Pamtre."
@decap_item_desc ITEM_WATMEL_BERRY, 0x83c37a9, " ingredient.\nPlant in loamy soil\nto grow WaTMel."
@decap_item_desc ITEM_DURIN_BERRY, 0x83c37df, " ingredient.\nPlant in loamy soil\nto grow Durin."
@decap_item_desc ITEM_BELUE_BERRY, 0x83c3814, " ingredient.\nPlant in loamy soil\nto grow Belue."
@decap_item_desc ITEM_LIECHI_BERRY, 0x83c3849, "A hold item that\nraises Attack in\na pinch."
@decap_item_desc ITEM_GANLON_BERRY, 0x83c3874, "A hold item that\nraises Defense in\na pinch."
@decap_item_desc ITEM_SALAC_BERRY, 0x83c38a0, "A hold item that\nraises Speed in\na pinch."
@decap_item_desc ITEM_PETAYA_BERRY, 0x83c38ca, "A hold item that\nraises Sp. Atk in\na pinch."
@decap_item_desc ITEM_APICOT_BERRY, 0x83c38f6, "A hold item that\nraises Sp. Def in\na pinch."
@decap_item_desc ITEM_LANSAT_BERRY, 0x83c3922, "A hold item that\nups the critical-\nhit rate in a pinch."
@decap_item_desc ITEM_STARF_BERRY, 0x83c395a, "A hold item that\nsharply boosts a\nstat in a pinch."
@decap_item_desc ITEM_ENIGMA_BERRY, 0x83c398d, "An unusual berry.\nProf. Birch gave it\nto you."
@decap_item_desc ITEM_0B0, 0x83c5562, ""
@decap_item_desc ITEM_0B1, 0x83c5562, ""
@decap_item_desc ITEM_0B2, 0x83c5562, ""
@decap_item_desc ITEM_YOUYOUYOU, 0x83c39c6, " you."
@decap_item_desc ITEM_GLOW_HERB, 0x83c39f9, "A hold item that\nrestores any\nlowered stat."
@decap_item_desc ITEM_DUMBBELLS, 0x83c3a25, "A hold item that\npromotes growth,\nbut reduces Speed."
@decap_item_desc ITEM_BRAIN_LINK, 0x83c3a5a, "A hold item that\ngets Exp. Points\nfrom battles."
@decap_item_desc ITEM_DEMON_HORN, 0x83c3a8a, "A hold item that\noccasionally allows\nthe first strike."
@decap_item_desc ITEM_KILIN_HORN, 0x83c3ac1, "A hold item that\ncalms spirits and\nfosters friendship."
@decap_item_desc ITEM_LOVESLAYER, 0x83c3af8, "A hold item that\nsnaps Pokémon out\nof infatuation."
@decap_item_desc ITEM_POWER_HAT, 0x83c3b2b, "Raises a move's\npower, but permits\nonly that move."
@decap_item_desc ITEM_SOME_TEETH, 0x83c3b5e, "Some sharp teeth.\nMay cause flinching\nwhen the foe's hit."
@decap_item_desc ITEM_FLASH_SCALES, 0x83c3b98, "A hold item that\nraises the power of\nBug-type moves."
@decap_item_desc ITEM_GAMBLE_FISH, 0x83c3bcd, "A fish that doubles\nthe money earned\nin battles. "
@decap_item_desc ITEM_DISPELL_TOKEN, 0x83c3bff, "A hold item that\nhelps repel wild\nPokémon."
@decap_item_desc ITEM_TAIJI_DUST, 0x83c3c2a, "Raises the Sp. stats\nof Téa Barqán\nand Luca Zamón."
@decap_item_desc ITEM_DEEP_SEA_TOOTH, 0x83c3c62, "A hold item that\nraises the Sp. Atk\nof Clamperl."
@decap_item_desc ITEM_DEEP_SEA_SCALE, 0x83c3c93, "A hold item that\nraises the Sp. Def\nof Clamperl."
@decap_item_desc ITEM_VOODOO_CANDY, 0x83c3cc4, "A hold item that\ncan be used to flee\nfrom a wild Pokémon."
@decap_item_desc ITEM_NEVERSTONE, 0x83c3cfe, "A wondrous stone\n& a hold item that\nprevents evolution."
@decap_item_desc ITEM_CHAOS_OF_ODEN, 0x83c3d36, "An amour type:  \noccasionally\nprevents fainting."
@decap_item_desc ITEM_LOVE_DRAIN, 0x83c3d67, "A hold item that\nboosts Exp. Points\nearned in battle."
@decap_item_desc ITEM_SNIPE_SCOPE, 0x83c3d9d, "A hold item that\nraises the critical-\nhit rate."
@decap_item_desc ITEM_EXCALIBUR, 0x83c3dcd, "A sword that\nraises the power of\nSteel-type moves."
@decap_item_desc ITEM_LEFTOVERS, 0x83c3e04, "A hold item that\ngradually restores\nHP in battle."
@decap_item_desc ITEM_RED_STEW, 0x83c3e36, "A pot of delicious\nred-coloured\nstew. Tasty! "
@decap_item_desc ITEM_MINER_TM, 0x83c3e64, "For miners.\nMust be unlocked\nto use.           "
@decap_item_desc ITEM_VOLCANO_POT, 0x83c3e94, "A hold item that\nraises the power of\nGround-type moves."
@decap_item_desc ITEM_OLD_BRICK, 0x83c3ecc, "A hold item that\nraises the power of\nRock-type moves."
@decap_item_desc ITEM_WONDERPLUM, 0x83c3f02, "A hold item that\nraises the power of\nGrass-type moves."
@decap_item_desc ITEM_BASS_GUITAR, 0x83c3f39, "A hold item that\nraises the power of\nDark-type moves."
@decap_item_desc ITEM_SPIKED_GLOVE, 0x83c3f6f, "A hold item that\nboosts Fighting-\ntype moves."
@decap_item_desc ITEM_ELECTRICHONEY, 0x83c3f9d, "A hold item that\nboosts Electric-\ntype moves."
@decap_item_desc ITEM_GODS_TEAR, 0x83c3fcb, "A hold item that\nraises the power of\nWater-type moves."
@decap_item_desc ITEM_ANADRIN_TALON, 0x83c4002, "A hold item that\nraises the power of\nFlying-type moves."
@decap_item_desc ITEM_SNAKE_EYES, 0x83c403a, "A hold item that\nraises the power of\nPoison-type moves."
@decap_item_desc ITEM_RAINBOWFROST, 0x83c4072, "A hold item that\nraises the power of\nIce-type moves."
@decap_item_desc ITEM_CURSED_SKULL, 0x83c40a7, "A hold item that\nraises the power of\nGhost-type moves."
@decap_item_desc ITEM_MEWTWO_BRAIN, 0x83c40de, "A hold item that\nboosts Psychic-\ntype moves."
@decap_item_desc ITEM_CINNAMON, 0x83c410b, "A hold item that\nraises the power of\nFire-type moves."
@decap_item_desc ITEM_TREASURE_BALL, 0x83c4141, "A hold item that\nraises the power of\nDragon-type moves."
@decap_item_desc ITEM_PLUS_BAND, 0x83c4179, "A hold item that\nraises the power of\nNormal-type moves."
@decap_item_desc ITEM_MINER_DOLL, 0x83c41b1, "Clockwork puppet\nwith a pickaxe."
@decap_item_desc ITEM_MEATY_BELL, 0x83c41d2, "A hold item that\nrestores HP upon\nstriking the foe."
@decap_item_desc ITEM_SOMA, 0x83c4206, "A hold item that\nslightly boosts\nWater-type moves."
@decap_item_desc ITEM_SAND_CLOAK, 0x83c4239, "A hold item that\nslightly lowers the\nfoe's accuracy."
@decap_item_desc ITEM_POKEPHONE, 0x83c426e, "A futuristic phone\ngiven to you\nby Prof. Birch."
@decap_item_desc ITEM_GASEOUS_ZINC, 0x83c42a3, "A hold item that\nraises Defense."
@decap_item_desc ITEM_POKEGEAR, 0x83c42c4, "Gleis's Pokégear.\nHe needs it\n              "
@decap_item_desc ITEM_PACHI_SWORD, 0x83c42f1, "Return it to\nits owner for\na reward."
@decap_item_desc ITEM_STATS_VIEWER, 0x83c5562, ""
@decap_item_desc ITEM_0E3, 0x83c5562, ""
@decap_item_desc ITEM_0E4, 0x83c5562, ""
@decap_item_desc ITEM_0E5, 0x83c5562, ""
@decap_item_desc ITEM_0E6, 0x83c5562, ""
@decap_item_desc ITEM_0E7, 0x83c5562, ""
@decap_item_desc ITEM_0E8, 0x83c5562, ""
@decap_item_desc ITEM_0E9, 0x83c5562, ""
@decap_item_desc ITEM_0EA, 0x83c5562, ""
@decap_item_desc ITEM_0EB, 0x83c5562, ""
@decap_item_desc ITEM_0EC, 0x83c5562, ""
@decap_item_desc ITEM_0ED, 0x83c5562, ""
@decap_item_desc ITEM_0EE, 0x83c5562, ""
@decap_item_desc ITEM_0EF, 0x83c5562, ""
@decap_item_desc ITEM_0F0, 0x83c5562, ""
@decap_item_desc ITEM_0F1, 0x83c5562, ""
@decap_item_desc ITEM_0F2, 0x83c5562, ""
@decap_item_desc ITEM_0F3, 0x83c5562, ""
@decap_item_desc ITEM_0F4, 0x83c5562, ""
@decap_item_desc ITEM_0F5, 0x83c5562, ""
@decap_item_desc ITEM_0F6, 0x83c5562, ""
@decap_item_desc ITEM_0F7, 0x83c5562, ""
@decap_item_desc ITEM_0F8, 0x83c5562, ""
@decap_item_desc ITEM_0F9, 0x83c5562, ""
@decap_item_desc ITEM_SECRET_KEY, 0x83c5562, ""
@decap_item_desc ITEM_HIDDEN_KEY, 0x83c5562, ""
@decap_item_desc ITEM_ARCANE_KEY, 0x83c5562, ""
@decap_item_desc ITEM_ABSTRUSE_KEY, 0x83c5562, ""
@decap_item_desc ITEM_RED_SCARF, 0x83c431a, "A hold item that\nraises Cool in\nContests."
@decap_item_desc ITEM_BLUE_SCARF, 0x83c4344, "A hold item that\nraises Beauty in\nContests."
@decap_item_desc ITEM_PINK_SCARF, 0x83c4370, "A hold item that\nraises Cute in\nContests."
@decap_item_desc ITEM_GREEN_SCARF, 0x83c439a, "A hold item that\nraises Smart in\nContests."
@decap_item_desc ITEM_YELLOW_SCARF, 0x83c43c5, "A hold item that\nraises Tough in\nContests."
@decap_item_desc ITEM_YELLOW_VESPA, 0x83c43f0, "A yellow Vespa  \nthat travels at   \nalarming speed. "
@decap_item_desc ITEM_COIN_CASE, 0x83c4425, "A case that holds\nup to 9,999 Coins."
@decap_item_desc ITEM_ITEMFINDER, 0x83c444a, "A device that\nsignals an invisible\nitem by sound."
@decap_item_desc ITEM_OLD_ROD, 0x83c447c, "Use by any body of\nwater to fish for\nwild Pokémon."
@decap_item_desc ITEM_CURSED_ROD, 0x83c44af, "An evil Rod that\nattracts strong\nwild monsters."
@decap_item_desc ITEM_KINGDRA_ROD, 0x83c44df, "The best Rod. \nCarved from a    \nKingdra spike."
@decap_item_desc ITEM_SS_TICKET, 0x83c450f, "The ticket required\nfor sailing on a\nferry."
@decap_item_desc ITEM_CATS_EYE, 0x83c453b, "It should be on a\nroad, but instead it's\nin bag."
@decap_item_desc ITEM_10B, 0x83c5562, ""
@decap_item_desc ITEM_WAILMER_PAIL, 0x83c456c, "A tool used for\nwatering Berries\nand plants."
@decap_item_desc ITEM_SPANNER, 0x83c4599, "An arclight\nspanner for     \nrepairing ships. "
@decap_item_desc ITEM_BONE_KEYRING, 0x83c45c8, "A ring for keys.\nIt's made of \nfinger bones."
@decap_item_desc ITEM_BROKEN_HEART, 0x83c45f5, "One of many that\nthe plague has\nleft in Hoenn. "
@decap_item_desc ITEM_AIR_TREKS, 0x83c4625, "Hi-tech skates for\nperforming the\nbest tricks.  "
@decap_item_desc ITEM_POKEBLOCK_CASE, 0x83c4656, "A case for holding\ns made with\na Berry Blender."
@decap_item_desc ITEM_GYM_TICKETS, 0x83c468b, "Two tickets to         \ntake you to Gym\nIsland. Why two?"
@decap_item_desc ITEM_SPATIAL_PASS, 0x83c46c4, "For one free    \nrocket ride.    \nBeloved of evil..."
@decap_item_desc ITEM_BLUE_FISH, 0x83c46f9, "One fish, two fish\n- just where do I\nstop with this?"
@decap_item_desc ITEM_PINK_INK, 0x83c472e, "Pink ink, for all\nyour ink-drinking\nneeds.           "
@decap_item_desc ITEM_ODD_KEYSTONE, 0x83c4764, "An odd-looking\nstone from \nthe shipwreck."
@decap_item_desc ITEM_HAJIKE_BIRD, 0x83c478e, "A little bird. This\nshould be delivered\nto a Hajikelist"
@decap_item_desc ITEM_RYDRAKE_WING, 0x83c47c6, "It has travelled  \nbetween worlds."
@decap_item_desc ITEM_SCRATCHKITTEN, 0x83c47e9, "A cute kitten. If\nit grows up, it\nmight fight."
@decap_item_desc ITEM_THUNDER_CUB, 0x83c481c, "A fierce little cub.\nMaybe it will\ngrow to be big."
@decap_item_desc ITEM_SCRUFFY_CHICK, 0x83c484f, "A scruffy little chick.\nWhat does it grow\ninto?   "
@decap_item_desc ITEM_FLASH_PUPPY, 0x83c4882, "A warm puppy. \nIt seems kind of\nproud and haughty."
@decap_item_desc ITEM_SPARKLY_PONY, 0x83c48b5, "A pony that shines\nwith inner light.\nMay grow up."
@decap_item_desc ITEM_VISITORS_PASS, 0x83c48e7, "A pass granting \naccess to areas in\nthe University."
@decap_item_desc ITEM_DRAGON_EGG, 0x83c491b, "This egg contains\nMeteor's daughter.\nIt's warm.    "
@decap_item_desc ITEM_ASTRAL_LENS, 0x83c494f, "A special camera\nlens that lets you\nsee through magic"
@decap_item_desc ITEM_TM01_FOCUS_PUNCH, 0x83c4985, "Powerful, but makes\nthe user flinch if\nhit by the foe."
@decap_item_desc ITEM_TM02_DRAGON_CLAW, 0x83c49bc, "Hooks and slashes\nthe foe with long,\nsharp claws."
@decap_item_desc ITEM_TM03_WATER_PULSE, 0x83c49ee, "Generates an\nultrasonic wave\nthat may confuse."
@decap_item_desc ITEM_TM04_CALM_MIND, 0x83c4a1d, "Raises Sp. Atk and\nSp. Def by focusing\nthe mind."
@decap_item_desc ITEM_TM05_ROAR, 0x83c4a4e, "A savage roar that\nmakes the foe flee \nto end the battle."
@decap_item_desc ITEM_TM06_TOXIC, 0x83c4a88, "Poisons the foe\nwith a toxin that\ngradually worsens."
@decap_item_desc ITEM_TM07_HAIL, 0x83c4abd, "Summons a hailstorm\nthat hurts all\ntypes except Ice."
@decap_item_desc ITEM_TM08_BULK_UP, 0x83c4af2, "Bulks up the body\nto boost both\nAttack & Defense."
@decap_item_desc ITEM_TM09_GRASSWHISTLE, 0x83c4b24, "A haunting tune\nthat may put the\nfoe to sleep. "
@decap_item_desc ITEM_TM10_HIDDEN_POWER, 0x83c4b54, "The attack power\nvaries among\ndifferent Pokémon."
@decap_item_desc ITEM_TM11_SUNNY_DAY, 0x83c4b85, "Raises the power of\nFire-type moves\nfor 5 turns."
@decap_item_desc ITEM_TM12_TAUNT, 0x83c4bb6, "Enrages the foe so\nit can only use\nattack moves."
@decap_item_desc ITEM_TM13_ICE_BEAM, 0x83c4be7, "Fires an icy cold\nbeam that may\nfreeze the foe."
@decap_item_desc ITEM_TM14_BLIZZARD, 0x83c4c17, "A vicious snow-and-\nwind attack that\nmay freeze the foe."
@decap_item_desc ITEM_TM15_HYPER_BEAM, 0x83c4c50, "Powerful, but needs\nrecharging the\nnext turn."
@decap_item_desc ITEM_TM16_LIGHT_SCREEN, 0x83c4c7e, "Creates a wall of\nlight that lowers\nSp. Atk damage."
@decap_item_desc ITEM_TM17_PROTECT, 0x83c4cb2, "Negates all damage,\nbut may fail if used\nin succession."
@decap_item_desc ITEM_TM18_RAIN_DANCE, 0x83c4cea, "Raises the power of\nWater-type moves\nfor 5 turns."
@decap_item_desc ITEM_TM19_GIGA_DRAIN, 0x83c4d1c, "Recovers half the\nHP of the damage \nthis move inflicts."
@decap_item_desc ITEM_TM20_SAFEGUARD, 0x83c4d54, "Prevents status\nabnormality with a\nmystical power."
@decap_item_desc ITEM_TM21_FRUSTRATION, 0x83c4d87, "The less the user\nlikes you, the more\npowerful this move."
@decap_item_desc ITEM_TM22_SOLARBEAM, 0x83c4dc1, "Absorbs sunlight in\nthe 1st turn, then\nattacks next turn."
@decap_item_desc ITEM_TM23_IRON_SLAM, 0x83c4dfb, "Slams the foe with\nan iron-hard body."
@decap_item_desc ITEM_TM24_THUNDERBOLT, 0x83c4e31, "A powerful electric\nattack that may\ncause paralysis."
@decap_item_desc ITEM_TM25_THUNDER, 0x83c4e66, "Strikes the foe\nwith a thunderbolt.\nIt may paralyze."
@decap_item_desc ITEM_TM26_EARTHQUAKE, 0x83c4e9b, "Causes a quake\nthat has no effect\non flying foes."
@decap_item_desc ITEM_TM27_RETURN, 0x83c4ecd, "The more the user\nlikes you, the more\npowerful this move."
@decap_item_desc ITEM_TM28_DIG, 0x83c4f07, "Digs underground\nthe 1st turn, then\nstrikes next turn."
@decap_item_desc ITEM_TM29_PSYCHIC, 0x83c4f3e, "A powerful psychic\nattack that may\nlower Sp. Def."
@decap_item_desc ITEM_TM30_SHADOW_BALL, 0x83c4f70, "Hurls a dark lump\nat the foe. It may\nlower Sp. Def."
@decap_item_desc ITEM_TM31_ICE_PUNCH, 0x83c4fa4, "A freezing punch that\ncan leave the foe\nfrozen solid. "
@decap_item_desc ITEM_TM32_DOUBLE_TEAM, 0x83c4fdb, "Creates illusory\ncopies to enhance\nelusiveness."
@decap_item_desc ITEM_TM33_REFLECT, 0x83c500b, "Creates a wall of\nlight that weakens\nphysical attacks."
@decap_item_desc ITEM_TM34_SHOCK_WAVE, 0x83c5042, "Zaps the foe with a\njolt of electricity\nthat never misses."
@decap_item_desc ITEM_TM35_FIRE_PUMP, 0x83c507d, "Looses a terrible\nburst of flames."
@decap_item_desc ITEM_TM36_SLUDGE_BOMB, 0x83c50ac, "Hurls sludge at the\nfoe. It may poison\nthe foe."
@decap_item_desc ITEM_TM37_SANDSTORM, 0x83c50dc, "Causes a sandstorm\nthat hits the foe\nover several turns."
@decap_item_desc ITEM_TM38_FIRE_BLAST, 0x83c5115, "A powerful fire\nattack that may\nburn the foe."
@decap_item_desc ITEM_TM39_ROCK_TOMB, 0x83c5143, "Stops the foe from\nmoving with rocks.\nMay lower Speed."
@decap_item_desc ITEM_TM40_BEAT_UP, 0x83c517a, "Calls everyone to\nbeat the crap out\nof the foe."
@decap_item_desc ITEM_TM41_TORMENT, 0x83c51aa, "Prevents the foe\nfrom using the same\nmove in a row."
@decap_item_desc ITEM_TM42_FACADE, 0x83c51de, "Raises Attack when\npoisoned, burned,\nor paralyzed."
@decap_item_desc ITEM_TM43_SECRET_POWER, 0x83c5211, "Adds an effect to\nattack depending\non the location."
@decap_item_desc ITEM_TM44_REST, 0x83c5245, "The user sleeps for\n2 turns to restore\nhealth and status."
@decap_item_desc ITEM_TM45_ATTRACT, 0x83c527f, "Makes it tough to\nattack a foe of the\nopposite gender."
@decap_item_desc ITEM_TM46_THIEF, 0x83c52b6, "While attacking,\nit may steal the\nfoe's held item."
@decap_item_desc ITEM_TM47_STEEL_WING, 0x83c52e9, "Spreads hard-edged\nwings and slams\ninto the foe."
@decap_item_desc ITEM_TM48_SKILL_SWAP, 0x83c531a, "Switches abilities\nwith the foe on the\nturn this is used."
@decap_item_desc ITEM_TM49_SNATCH, 0x83c5354, "Steals the effects\nof the move the foe\nis trying to use."
@decap_item_desc ITEM_TM50_OVERHEAT, 0x83c538d, "Enables full-power\nattack, but sharply\nlowers Sp. Atk."
@decap_item_desc ITEM_HM01_CUT, 0x83c53c4, "Attacks the foe\nwith sharp blades\nor claws."
@decap_item_desc ITEM_HM02_FLY, 0x83c53f0, "Flies up on the\nfirst turn, then\nattacks next turn."
@decap_item_desc ITEM_HM03_SURF, 0x83c5424, "Creates a huge\nwave, then crashes\nit down on the foe."
@decap_item_desc ITEM_HM04_STRENGTH, 0x83c545a, "Builds enormous\npower, then slams\nthe foe."
@decap_item_desc ITEM_HM05_FLASH, 0x83c5485, "Looses a powerful\nblast of light that\nreduces accuracy."
@decap_item_desc ITEM_HM06_ROCK_SMASH, 0x83c54bd, "A rock-crushingly\ntough attack that\nmay lower Defense."
@decap_item_desc ITEM_HM07_WATERFALL, 0x83c54f4, "Attacks the foe\nwith enough power\nto climb waterfalls."
@decap_item_desc ITEM_HM08_DIVE, 0x83c552b, "Dives underwater\nthe 1st turn, then\nattacks next turn."
@decap_item_desc ITEM_15B, 0x83c5562, ""
@decap_item_desc ITEM_15C, 0x83c5562, ""