.macro @decap_trainer_name, i, name
@decap_table 0x81f0500, 12, 40, i, name
.endmacro

@decap_trainer_name TRAINER_ROLV_1, "Rolv"
@decap_trainer_name TRAINER_THERESA, "Theresa"
@decap_trainer_name TRAINER_MIGUEL_1, "Miguel"
@decap_trainer_name TRAINER_FRANKLIN, "Franklin"
@decap_trainer_name TRAINER_MARVIN, "Marvin"
@decap_trainer_name TRAINER_TOMAS, "Tomás"
@decap_trainer_name TRAINER_VITRUVIO, "Vitruvio"
@decap_trainer_name TRAINER_BELDUM, "Beldum"
@decap_trainer_name TRAINER_METEOR_1, "Meteor"
@decap_trainer_name TRAINER_TOMU, "Tomu"
@decap_trainer_name TRAINER_SHIRASAGI, "Shirasagi"
@decap_trainer_name TRAINER_NAOTA, "Naota"
@decap_trainer_name TRAINER_PAOLO, "Paolo"
@decap_trainer_name TRAINER_NIIZUMA, "Niizuma"
@decap_trainer_name TRAINER_WATTSON_1, "Wattson"
@decap_trainer_name TRAINER_WATTSON_2, "Wattson"
@decap_trainer_name TRAINER_FOOTMAN_1, "Footman"
@decap_trainer_name TRAINER_AKATSUKI, "Akatsuki"
@decap_trainer_name TRAINER_MIKOV_1, "Mikov"
@decap_trainer_name TRAINER_BOBOV_1, "Bobov"
@decap_trainer_name TRAINER_GUNKOV_1, "Gunkov"
@decap_trainer_name TRAINER_KARKOV_1, "Karkov"
@decap_trainer_name TRAINER_ROBOTNOV_1, "Robotnov"
@decap_trainer_name TRAINER_ROLV_2, "Rolv"
@decap_trainer_name TRAINER_SPUTNOV_1, "Sputnov"
@decap_trainer_name TRAINER_VLADOV_1, "Vladov"
@decap_trainer_name TRAINER_ADOLV_1, "Adolv"
@decap_trainer_name TRAINER_ASIMOV_1, "Asimov"
@decap_trainer_name TRAINER_LIAM, "Liam"
@decap_trainer_name TRAINER_LIZZIE, "Lizzie"
@decap_trainer_name TRAINER_MIKOV_2, "Mikov"
@decap_trainer_name TRAINER_BOBOV_2, "Bobov"
@decap_trainer_name TRAINER_GUNKOV_2, "Gunkov"
@decap_trainer_name TRAINER_KARKOV_2, "Karkov"
@decap_trainer_name TRAINER_ROBOTNOV_2, "Robotnov"
@decap_trainer_name TRAINER_ED, "Ed"
@decap_trainer_name TRAINER_TESRAEL, "Tesrael"
@decap_trainer_name TRAINER_LILY, "Lily"
@decap_trainer_name TRAINER_RAN_MAO, "Ran-Mao"
@decap_trainer_name TRAINER_SPUTNOV_2, "Sputnov"
@decap_trainer_name TRAINER_VLADOV_2, "Vladov"
@decap_trainer_name TRAINER_ADOLV_2, "Adolv"
@decap_trainer_name TRAINER_ASIMOV_2, "Asimov"
@decap_trainer_name TRAINER_CRANKSHAFT, "Crankshaft"
@decap_trainer_name TRAINER_ZAPPIZOR, "Zappizor"
@decap_trainer_name TRAINER_ARTURO, "Arturo"
@decap_trainer_name TRAINER_DOUBLEACT_1, "Double Act"
@decap_trainer_name TRAINER_GAOLER_1, "Gaoler"
@decap_trainer_name TRAINER_GAOLER_2, "Gaoler"
@decap_trainer_name TRAINER_MALFEASANCE, "Malfeasance"
@decap_trainer_name TRAINER_TINAANDBRUCE_1, "Tina &Bruce"
@decap_trainer_name TRAINER_TINAANDBRUCE_2, "Tina &Bruce"
@decap_trainer_name TRAINER_TINAANDBRUCE_3, "Tina &Bruce"
@decap_trainer_name TRAINER_TINAANDBRUCE_4, "Tina &Bruce"
@decap_trainer_name TRAINER_TINAANDBRUCE_5, "Tina &Bruce"
@decap_trainer_name TRAINER_TINAANDBRUCE_6, "Tina &Bruce"
@decap_trainer_name TRAINER_DUBLIQUE, "Dubliqué"
@decap_trainer_name TRAINER_MIKE, "Mike"
@decap_trainer_name TRAINER_GWEN, "Gwen "
@decap_trainer_name TRAINER_CARMEN, "Carmen"
@decap_trainer_name TRAINER_GENGUI, "Gen Gui"
@decap_trainer_name TRAINER_RICKY_1, "Ricky"
@decap_trainer_name TRAINER_LOLA, "Lola"
@decap_trainer_name TRAINER_BUCCHA, "Buccha"
@decap_trainer_name TRAINER_SIMON, "Simon"
@decap_trainer_name TRAINER_MACGUFFIN, "Macguffin"
@decap_trainer_name TRAINER_RICKY_2, "Ricky"
@decap_trainer_name TRAINER_LOLIDRAGON, "Lolidragon"
@decap_trainer_name TRAINER_LIRIACHEN, "Liria Chen"
@decap_trainer_name TRAINER_MCDOUGAL, "Mcdougal"
@decap_trainer_name TRAINER_RANDALL, "Randall"
@decap_trainer_name TRAINER_PARKER, "Parker"
@decap_trainer_name TRAINER_GEORGE, "George"
@decap_trainer_name TRAINER_BERKE, "Berke"
@decap_trainer_name TRAINER_MAJIDE, "Majide"
@decap_trainer_name TRAINER_VINCENT, "Vincent"
@decap_trainer_name TRAINER_LEROY, "Leroy"
@decap_trainer_name TRAINER_ICHI, "Ichi"
@decap_trainer_name TRAINER_MANGOMAN, "Mango Man"
@decap_trainer_name TRAINER_ALBERTO, "Alberto"
@decap_trainer_name TRAINER_ENIGMA, "Enigma"
@decap_trainer_name TRAINER_CORLEONE, "Corleone"
@decap_trainer_name TRAINER_CASTANO, "Castaño"
@decap_trainer_name TRAINER_FIVENINJA_1, "Five Ninja"
@decap_trainer_name TRAINER_INIGO, "Iñigo"
@decap_trainer_name TRAINER_MANFRED_1, "Manfred"
@decap_trainer_name TRAINER_WILTON, "Wilton"
@decap_trainer_name TRAINER_GIMLETEYE, "Gimlet Eye"
@decap_trainer_name TRAINER_MARY, "Mary"
@decap_trainer_name TRAINER_LORI, "Lori"
@decap_trainer_name TRAINER_JODY, "Jody"
@decap_trainer_name TRAINER_MEI_RIN, "Mei-Rin"
@decap_trainer_name TRAINER_ELAINE, "Elaine"
@decap_trainer_name TRAINER_JEMIMA, "Jemima"
@decap_trainer_name TRAINER_BLAIRWITCH, "Blair Witch"
@decap_trainer_name TRAINER_BETHANY, "Bethany"
@decap_trainer_name TRAINER_FISHGIRL_1, "Fishgirl"
@decap_trainer_name TRAINER_SUSAN, "Susan"
@decap_trainer_name TRAINER_FIVENINJA_2, "Five Ninja"
@decap_trainer_name TRAINER_JULIANNE, "Julianne"
@decap_trainer_name TRAINER_BROOKE, "Brooke"
@decap_trainer_name TRAINER_WHITNEY, "Whitney"
@decap_trainer_name TRAINER_MARLENE, "Marlene"
@decap_trainer_name TRAINER_MIKOV_3, "Mikov"
@decap_trainer_name TRAINER_PATRICIA, "Patricia"
@decap_trainer_name TRAINER_RUBRIC, "Rubric"
@decap_trainer_name TRAINER_TCHAIKOVSKY, "Tchaikovsky"
@decap_trainer_name TRAINER_TABBY, "Tabby"
@decap_trainer_name TRAINER_BILLSTOKEY, "Bill Stokey"
@decap_trainer_name TRAINER_VALERIE, "Valerie"
@decap_trainer_name TRAINER_BOBOV_3, "Bobov"
@decap_trainer_name TRAINER_GUNKOV_3, "Gunkov"
@decap_trainer_name TRAINER_KARKOV_3, "Karkov"
@decap_trainer_name TRAINER_TILLY, "Tilly"
@decap_trainer_name TRAINER_DANI, "Dani"
@decap_trainer_name TRAINER_BRIANNA, "Brianna"
@decap_trainer_name TRAINER_CINDY, "Cindy"
@decap_trainer_name TRAINER_ROBOTNOV_3, "Robotnov"
@decap_trainer_name TRAINER_ANETTE, "Anette"
@decap_trainer_name TRAINER_ROLV_3, "Rolv"
@decap_trainer_name TRAINER_SPUTNOV_3, "Sputnov"
@decap_trainer_name TRAINER_VLADOV_3, "Vladov"
@decap_trainer_name TRAINER_ADOLV_3, "Adolv"
@decap_trainer_name TRAINER_WEISHI, "Wei Shi"
@decap_trainer_name TRAINER_CHAOYUN, "Chao Yun"
@decap_trainer_name TRAINER_SHUYI, "Shu Yi"
@decap_trainer_name TRAINER_HIRO, "Hiro"
@decap_trainer_name TRAINER_CONNIE, "Connie"
@decap_trainer_name TRAINER_BRIDGET, "Bridget"
@decap_trainer_name TRAINER_OLIVIA, "Olivia"
@decap_trainer_name TRAINER_TIFFANY, "Tiffany"
@decap_trainer_name TRAINER_JESSICA, "Jessica"
@decap_trainer_name TRAINER_ASIMOV_3, "Asimov"
@decap_trainer_name TRAINER_BARBARA, "Barbara"
@decap_trainer_name TRAINER_MIMI, "Mimi"
@decap_trainer_name TRAINER_RICHIE, "Richie"
@decap_trainer_name TRAINER_OROBAS, "Orobas"
@decap_trainer_name TRAINER_GARRET, "Garret"
@decap_trainer_name TRAINER_WINSTON_1, "Winston"
@decap_trainer_name TRAINER_DUNCAN, "Duncan"
@decap_trainer_name TRAINER_DIRTHUGGER, "Dirthugger"
@decap_trainer_name TRAINER_BIFBOFBEE_1, "Bif Bof Bee"
@decap_trainer_name TRAINER_STEVE_1, "Steve"
@decap_trainer_name TRAINER_CHRIS, "Chris"
@decap_trainer_name TRAINER_MACHI, "Machi"
@decap_trainer_name TRAINER_KENN, "Kenn"
@decap_trainer_name TRAINER_STEVE_2, "Steve"
@decap_trainer_name TRAINER_ROLV_4, "Rolv"
@decap_trainer_name TRAINER_EOWYN, "Eowyn"
@decap_trainer_name TRAINER_BRUNELLA, "Brunella"
@decap_trainer_name TRAINER_LUIS, "Luis"
@decap_trainer_name TRAINER_VEGAS, "Vegas"
@decap_trainer_name TRAINER_PEKABO, "Pekabo"
@decap_trainer_name TRAINER_TARQUIN, "Tarquin"
@decap_trainer_name TRAINER_MIKHAIL, "Mikhail"
@decap_trainer_name TRAINER_JACKABY, "Jackaby"
@decap_trainer_name TRAINER_MATTHEW, "Matthew"
@decap_trainer_name TRAINER_ERLANDU, "Erlandu"
@decap_trainer_name TRAINER_PETRUCHIO, "Petruchio"
@decap_trainer_name TRAINER_OBLIGATION, "Obligation"
@decap_trainer_name TRAINER_CODY, "Cody"
@decap_trainer_name TRAINER_STAN, "Stan"
@decap_trainer_name TRAINER_CHUCKLES, "Chuckles"
@decap_trainer_name TRAINER_SEAMUSII, "Seamus II"
@decap_trainer_name TRAINER_BIFBOFBEE_2, "Bif Bof Bee"
@decap_trainer_name TRAINER_GONZALES, "Gonzales"
@decap_trainer_name TRAINER_SHUNKLE, "Shunkle"
@decap_trainer_name TRAINER_BENJI, "Benji"
@decap_trainer_name TRAINER_DONATELLO, "Donatello"
@decap_trainer_name TRAINER_MUSHUSHSHU, "Mushushshu"
@decap_trainer_name TRAINER_DANNY, "Danny"
@decap_trainer_name TRAINER_FUNHOUSE, "Fun House"
@decap_trainer_name TRAINER_DUDLEY, "Dudley"
@decap_trainer_name TRAINER_CHAD, "Chad"
@decap_trainer_name TRAINER_TONY, "Tony"
@decap_trainer_name TRAINER_FOOTMAN_2, "Footman"
@decap_trainer_name TRAINER_MANFRED_2, "Manfred"
@decap_trainer_name TRAINER_KERRI, "Kerri"
@decap_trainer_name TRAINER_KONGAMOTO, "Kongamoto"
@decap_trainer_name TRAINER_FINALSMASH, "Final Smash"
@decap_trainer_name TRAINER_HATSUHARU, "Hatsuharu"
@decap_trainer_name TRAINER_ICHIROU, "Ichirou"
@decap_trainer_name TRAINER_NOB, "Nob"
@decap_trainer_name TRAINER_MARY_SUE, "Mary-Sue"
@decap_trainer_name TRAINER_ALCAPONE, "Al Capone"
@decap_trainer_name TRAINER_ANJOU, "Anjou"
@decap_trainer_name TRAINER_MISSY, "Missy"
@decap_trainer_name TRAINER_YUJI, "Yuji"
@decap_trainer_name TRAINER_DAISUKE, "Daisuke"
@decap_trainer_name TRAINER_ZACHARY, "Zachary"
@decap_trainer_name TRAINER_KIRK, "Kirk"
@decap_trainer_name TRAINER_SCOTT, "Scott"
@decap_trainer_name TRAINER_HARVEY_1, "Harvey"
@decap_trainer_name TRAINER_SHAWN, "Shawn"
@decap_trainer_name TRAINER_RANDY, "Randy"
@decap_trainer_name TRAINER_DALTON, "Dalton"
@decap_trainer_name TRAINER_BESS, "Bess"
@decap_trainer_name TRAINER_TOHRU, "Tohru"
@decap_trainer_name TRAINER_KYOU, "Kyou"
@decap_trainer_name TRAINER_YUKI, "Yuki"
@decap_trainer_name TRAINER_YONGLIANG, "Yongliang"
@decap_trainer_name TRAINER_FLINT, "Flint"
@decap_trainer_name TRAINER_TINGFENG, "Ting Feng"
@decap_trainer_name TRAINER_JAKE, "Jake"
@decap_trainer_name TRAINER_GUIREN, "Guiren"
@decap_trainer_name TRAINER_BERNIE_1, "Bernie"
@decap_trainer_name TRAINER_LONGWEI, "Longwei"
@decap_trainer_name TRAINER_BERNIE_2, "Bernie"
@decap_trainer_name TRAINER_MIKOV_4, "Mikov"
@decap_trainer_name TRAINER_BOBOV_4, "Bobov"
@decap_trainer_name TRAINER_KEN, "Ken"
@decap_trainer_name TRAINER_HAYATE, "Hayate"
@decap_trainer_name TRAINER_WESTLEY, "Westley"
@decap_trainer_name TRAINER_SHANE, "Shane"
@decap_trainer_name TRAINER_JUSTIN, "Justin"
@decap_trainer_name TRAINER_CHINBAO, "Chin Bao"
@decap_trainer_name TRAINER_JEFF, "Jeff"
@decap_trainer_name TRAINER_HORODA, "Horoda"
@decap_trainer_name TRAINER_ETHAN, "Ethan"
@decap_trainer_name TRAINER_GAOLER_3, "Gaoler"
@decap_trainer_name TRAINER_BRAVO, "Bravo"
@decap_trainer_name TRAINER_MINA, "Mina"
@decap_trainer_name TRAINER_BRENT, "Brent"
@decap_trainer_name TRAINER_DONALD, "Donald"
@decap_trainer_name TRAINER_TAYLOR, "Taylor"
@decap_trainer_name TRAINER_CHIKICORMA, "Chiki Corma"
@decap_trainer_name TRAINER_DEREK, "Derek"
@decap_trainer_name TRAINER_HATORI, "Hatori"
@decap_trainer_name TRAINER_MOMIJI, "Momiji"
@decap_trainer_name TRAINER_BRANDON, "Brandon"
@decap_trainer_name TRAINER_GUNKOV_4, "Gunkov"
@decap_trainer_name TRAINER_EDWARD, "Edward"
@decap_trainer_name TRAINER_AQUIFER, "Aquifer"
@decap_trainer_name TRAINER_THUNDORA, "Thundora"
@decap_trainer_name TRAINER_MONS, "Mons"
@decap_trainer_name TRAINER_DONPUNCHIES, "Donpunchies"
@decap_trainer_name TRAINER_JOSHUA, "Joshua"
@decap_trainer_name TRAINER_YVES, "Yves"
@decap_trainer_name TRAINER_CAMERON_1, "Cameron"
@decap_trainer_name TRAINER_CAMERON_2, "Cameron"
@decap_trainer_name TRAINER_CAMERON_3, "Cameron"
@decap_trainer_name TRAINER_CAMERON_4, "Cameron"
@decap_trainer_name TRAINER_FOOTMAN_3, "Footman"
@decap_trainer_name TRAINER_VENTANA, "Ventana"
@decap_trainer_name TRAINER_GAIA, "Gaia"
@decap_trainer_name TRAINER_FLAMMA, "Flamma"
@decap_trainer_name TRAINER_CHERIE, "Cherie"
@decap_trainer_name TRAINER_ALEXIS, "Alexis"
@decap_trainer_name TRAINER_SHUBITZ, "Shubitz"
@decap_trainer_name TRAINER_JACKI_1, "Jacki"
@decap_trainer_name TRAINER_GLEIS_1, "Gleis"
@decap_trainer_name TRAINER_JACKI_2, "Jacki"
@decap_trainer_name TRAINER_TEX, "Tex"
@decap_trainer_name TRAINER_WINSTON_2, "Winston"
@decap_trainer_name TRAINER_TUCKER, "Tucker"
@decap_trainer_name TRAINER_THOMAS, "Thomas"
@decap_trainer_name TRAINER_WALTER, "Walter"
@decap_trainer_name TRAINER_KARKOV_4, "Karkov"
@decap_trainer_name TRAINER_ROBOTNOV_4, "Robotnov"
@decap_trainer_name TRAINER_ROLV_5, "Rolv"
@decap_trainer_name TRAINER_CAITLIN, "Caitlin"
@decap_trainer_name TRAINER_BENNY_1, "Benny"
@decap_trainer_name TRAINER_GLACIA, "Glacia"
@decap_trainer_name TRAINER_INDIGO, "Indigo"
@decap_trainer_name TRAINER_ROXANNE, "Roxanne"
@decap_trainer_name TRAINER_HARUKO, "Haruko"
@decap_trainer_name TRAINER_WATTSON_3, "Wattson"
@decap_trainer_name TRAINER_VERACITY, "Veracity"
@decap_trainer_name TRAINER_NORMAN, "Norman"
@decap_trainer_name TRAINER_WINONA, "Winona"
@decap_trainer_name TRAINER_TATEANDLIZA, "Tate&Liza"
@decap_trainer_name TRAINER_ESAU, "Esau"
@decap_trainer_name TRAINER_MORPH_1, "Morph"
@decap_trainer_name TRAINER_TED, "Ted"
@decap_trainer_name TRAINER_PAUL, "Paul"
@decap_trainer_name TRAINER_MORPH_2, "Morph"
@decap_trainer_name TRAINER_JERRY, "Jerry"
@decap_trainer_name TRAINER_NOTTINGHAM, "Nottingham"
@decap_trainer_name TRAINER_BANDITO, "Bandito"
@decap_trainer_name TRAINER_SCISSORA, "Scissora"
@decap_trainer_name TRAINER_GEORGIA, "Georgia"
@decap_trainer_name TRAINER_KAREN, "Karen"
@decap_trainer_name TRAINER_FOOTMAN_4, "Footman"
@decap_trainer_name TRAINER_FOOTMAN_5, "Footman"
@decap_trainer_name TRAINER_FIVENINJA_3, "Five Ninja"
@decap_trainer_name TRAINER_JADEANDSARA, "Jade & Sara"
@decap_trainer_name TRAINER_KATANDBERT, "Kat & Bert"
@decap_trainer_name TRAINER_ANNAANDMEG_1, "Anna & Meg"
@decap_trainer_name TRAINER_SASHA, "Sasha"
@decap_trainer_name TRAINER_DOUBLEACT_2, "Double Act"
@decap_trainer_name TRAINER_ANNAANDMEG_2, "Anna & Meg"
@decap_trainer_name TRAINER_MUGWIN_1, "Mugwin"
@decap_trainer_name TRAINER_MIGUEL_2, "Miguel"
@decap_trainer_name TRAINER_COLTON, "Colton"
@decap_trainer_name TRAINER_CHLOE_1, "Chloe"
@decap_trainer_name TRAINER_FISHGIRL_2, "Fishgirl"
@decap_trainer_name TRAINER_MANZANA, "Manzana"
@decap_trainer_name TRAINER_MIGUEL_3, "Miguel"
@decap_trainer_name TRAINER_MUGWIN_2, "Mugwin"
@decap_trainer_name TRAINER_UGBUOON, "Ugbuoon"
@decap_trainer_name TRAINER_MARISSA, "Marissa"
@decap_trainer_name TRAINER_ROCKIT, "Rockit"
@decap_trainer_name TRAINER_ISABEL_1, "Isabel"
@decap_trainer_name TRAINER_ISABEL_2, "Isabel"
@decap_trainer_name TRAINER_TARNATION, "Tarnation"
@decap_trainer_name TRAINER_HANNAH, "Hannah"
@decap_trainer_name TRAINER_GUARDIAN, "Guardian"
@decap_trainer_name TRAINER_CHLOE_2, "Chloe"
@decap_trainer_name TRAINER_PERKINS, "Perkins"
@decap_trainer_name TRAINER_MAGDALENE, "Magdalene"
@decap_trainer_name TRAINER_TIMOTHY, "Timothy"
@decap_trainer_name TRAINER_MUGWIN_3, "Mugwin"
@decap_trainer_name TRAINER_QINGXUE, "Qing Xue"
@decap_trainer_name TRAINER_SHELBY_1, "Shelby"
@decap_trainer_name TRAINER_KATHY, "Kathy"
@decap_trainer_name TRAINER_SHELBY_2, "Shelby"
@decap_trainer_name TRAINER_SHELBY_3, "Shelby"
@decap_trainer_name TRAINER_CALVIN_1, "Calvin"
@decap_trainer_name TRAINER_LAURENCE, "Laurence"
@decap_trainer_name TRAINER_JOSH, "Josh"
@decap_trainer_name TRAINER_TOMMY, "Tommy"
@decap_trainer_name TRAINER_ASMODEUS, "Asmodeus"
@decap_trainer_name TRAINER_BEN, "Ben"
@decap_trainer_name TRAINER_BELIAL_1, "Belial"
@decap_trainer_name TRAINER_KEVIN, "Kevin"
@decap_trainer_name TRAINER_NEAL, "Neal"
@decap_trainer_name TRAINER_FOOTMAN_6, "Footman"
@decap_trainer_name TRAINER_CALVIN_2, "Calvin"
@decap_trainer_name TRAINER_CALVIN_3, "Calvin"
@decap_trainer_name TRAINER_CLINT, "Clint"
@decap_trainer_name TRAINER_SENEX_1, "Senex"
@decap_trainer_name TRAINER_EDDIE, "Eddie"
@decap_trainer_name TRAINER_ALLEN, "Allen"
@decap_trainer_name TRAINER_FOOTMAN_7, "Footman"
@decap_trainer_name TRAINER_FENGLEI, "Feng Lei"
@decap_trainer_name TRAINER_TIMANDTINA, "Tim & Tina"
@decap_trainer_name TRAINER_DUNSTAN, "Dunstan"
@decap_trainer_name TRAINER_FOOTMAN_8, "Footman"
@decap_trainer_name TRAINER_SMASHSHOT, "Smash Shot"
@decap_trainer_name TRAINER_NED, "Ned"
@decap_trainer_name TRAINER_MASHIMA, "Mashima"
@decap_trainer_name TRAINER_FOOTMAN_9, "Footman"
@decap_trainer_name TRAINER_FERNANDO, "Fernando"
@decap_trainer_name TRAINER_OSWALD, "Oswald"
@decap_trainer_name TRAINER_RICARDO, "Ricardo"
@decap_trainer_name TRAINER_ELLIOT_1, "Elliot"
@decap_trainer_name TRAINER_TEMULENCE_1, "Temulence"
@decap_trainer_name TRAINER_ELLIOT_2, "Elliot"
@decap_trainer_name TRAINER_FIVENINJA_4, "Five Ninja"
@decap_trainer_name TRAINER_UNBONE, "Unbone"
@decap_trainer_name TRAINER_JACOB, "Jacob"
@decap_trainer_name TRAINER_ANTHONY, "Anthony"
@decap_trainer_name TRAINER_BENJAMIN_1, "Benjamin"
@decap_trainer_name TRAINER_BENJAMIN_2, "Benjamin"
@decap_trainer_name TRAINER_BENJAMIN_3, "Benjamin"
@decap_trainer_name TRAINER_BENJAMIN_4, "Benjamin"
@decap_trainer_name TRAINER_BENJAMIN_5, "Benjamin"
@decap_trainer_name TRAINER_ABIGAIL_1, "Abigail"
@decap_trainer_name TRAINER_JASMINE, "Jasmine"
@decap_trainer_name TRAINER_ABIGAIL_2, "Abigail"
@decap_trainer_name TRAINER_ABIGAIL_3, "Abigail"
@decap_trainer_name TRAINER_ABIGAIL_4, "Abigail"
@decap_trainer_name TRAINER_ABIGAIL_5, "Abigail"
@decap_trainer_name TRAINER_HEIWAJIMA, "Heiwajima"
@decap_trainer_name TRAINER_DYLAN_1, "Dylan"
@decap_trainer_name TRAINER_DYLAN_2, "Dylan"
@decap_trainer_name TRAINER_DYLAN_3, "Dylan"
@decap_trainer_name TRAINER_DYLAN_4, "Dylan"
@decap_trainer_name TRAINER_MARIA_1, "Maria"
@decap_trainer_name TRAINER_WAYNE, "Wayne"
@decap_trainer_name TRAINER_WOODY, "Woody"
@decap_trainer_name TRAINER_MARIA_2, "Maria"
@decap_trainer_name TRAINER_MARIA_3, "Maria"
@decap_trainer_name TRAINER_MONKLEY, "Monkley"
@decap_trainer_name TRAINER_THESHERIFF, "The Sheriff"
@decap_trainer_name TRAINER_CYRUS, "Cyrus"
@decap_trainer_name TRAINER_MANLYHERO, "Manly Hero"
@decap_trainer_name TRAINER_HUNKY_DORY, "Hunky-Dory"
@decap_trainer_name TRAINER_ISAIAH_1, "Isaiah"
@decap_trainer_name TRAINER_ISAIAH_2, "Isaiah"
@decap_trainer_name TRAINER_ISAIAH_3, "Isaiah"
@decap_trainer_name TRAINER_MAGNUSVII, "Magnus VII"
@decap_trainer_name TRAINER_METEOR_2, "Meteor"
@decap_trainer_name TRAINER_MAXINE, "Maxine"
@decap_trainer_name TRAINER_METEOR_3, "Meteor"
@decap_trainer_name TRAINER_PERJURY, "Perjury"
@decap_trainer_name TRAINER_MARIEBAIN, "Marie Bain"
@decap_trainer_name TRAINER_KATELYN_1, "Katelyn"
@decap_trainer_name TRAINER_KATELYN_2, "Katelyn"
@decap_trainer_name TRAINER_KATELYN_3, "Katelyn"
@decap_trainer_name TRAINER_KATELYN_4, "Katelyn"
@decap_trainer_name TRAINER_NICOLAS_1, "Nicolas"
@decap_trainer_name TRAINER_NICOLAS_2, "Nicolas"
@decap_trainer_name TRAINER_NICOLAS_3, "Nicolas"
@decap_trainer_name TRAINER_NICKYP, "Nicky P."
@decap_trainer_name TRAINER_FORTUNO, "Fortuno"
@decap_trainer_name TRAINER_LIUBEI, "Liu Bei"
@decap_trainer_name TRAINER_JAIME, "Jaime"
@decap_trainer_name TRAINER_HUGHIE, "Hughie"
@decap_trainer_name TRAINER_PHILIP, "Philip"
@decap_trainer_name TRAINER_JARED, "Jared"
@decap_trainer_name TRAINER_MITCHELL, "Mitchell"
@decap_trainer_name TRAINER_TANNER, "Tanner"
@decap_trainer_name TRAINER_WILL, "Will"
@decap_trainer_name TRAINER_MAYBEWITCH, "Maybe Witch"
@decap_trainer_name TRAINER_BADFAIRY, "Bad Fairy"
@decap_trainer_name TRAINER_BENNY_2, "Benny"
@decap_trainer_name TRAINER_HESTER, "Hester"
@decap_trainer_name TRAINER_GLEIS_2, "Gleis"
@decap_trainer_name TRAINER_TEMULENCE_2, "Temulence"
@decap_trainer_name TRAINER_ROBERT, "Robert"
@decap_trainer_name TRAINER_BURKE, "Burke"
@decap_trainer_name TRAINER_OSTAFAN, "Ostafan"
@decap_trainer_name TRAINER_DECKARD, "Deckard"
@decap_trainer_name TRAINER_ROGER, "Roger"
@decap_trainer_name TRAINER_BRET, "Bret"
@decap_trainer_name TRAINER_MAKOTO, "Makoto"
@decap_trainer_name TRAINER_HIDEO, "Hideo"
@decap_trainer_name TRAINER_TANCRED, "Tancred"
@decap_trainer_name TRAINER_CHARLES, "Charles"
@decap_trainer_name TRAINER_LAO_1, "Lao"
@decap_trainer_name TRAINER_LAO_2, "Lao"
@decap_trainer_name TRAINER_SCHWARTZ_1, "Schwartz"
@decap_trainer_name TRAINER_SCHWARTZ_2, "Schwartz"
@decap_trainer_name TRAINER_TYRONE, "Tyrone"
@decap_trainer_name TRAINER_MATTEO, "Matteo"
@decap_trainer_name TRAINER_LAURA, "Laura"
@decap_trainer_name TRAINER_CORA, "Cora"
@decap_trainer_name TRAINER_JILL, "Jill"
@decap_trainer_name TRAINER_CYNDY_1, "Cyndy"
@decap_trainer_name TRAINER_CYNDY_2, "Cyndy"
@decap_trainer_name TRAINER_SCHWARTZ_3, "Schwartz"
@decap_trainer_name TRAINER_SCHWARTZ_4, "Schwartz"
@decap_trainer_name TRAINER_VINNIE, "Vinnie"
@decap_trainer_name TRAINER_ANGELWITCH, "Angel Witch"
@decap_trainer_name TRAINER_EASTWITCH, "East Witch"
@decap_trainer_name TRAINER_MADELINE_1, "Madeline"
@decap_trainer_name TRAINER_STANISLAUS, "Stanislaus"
@decap_trainer_name TRAINER_BOSS, "Boss"
@decap_trainer_name TRAINER_MADELINE_2, "Madeline"
@decap_trainer_name TRAINER_BEVERLY, "Beverly"
@decap_trainer_name TRAINER_DAWN, "Dawn"
@decap_trainer_name TRAINER_BEATRICE, "Beatrice"
@decap_trainer_name TRAINER_DENISE, "Denise"
@decap_trainer_name TRAINER_BETH, "Beth"
@decap_trainer_name TRAINER_KRIS, "Kris"
@decap_trainer_name TRAINER_JESUS, "Jésus"
@decap_trainer_name TRAINER_ALICE, "Alice"
@decap_trainer_name TRAINER_WORCESTERIA, "Worcesteria"
@decap_trainer_name TRAINER_HUAJIAO, "Hua Jiao"
@decap_trainer_name TRAINER_TANYA, "Tanya"
@decap_trainer_name TRAINER_SHARON, "Sharon"
@decap_trainer_name TRAINER_ENDLESS, "Endless"
@decap_trainer_name TRAINER_KOTOKABE, "Kotokabe"
@decap_trainer_name TRAINER_CATALANA, "Catalána"
@decap_trainer_name TRAINER_CREPERIE, "Créperie"
@decap_trainer_name TRAINER_DONGIGA, "Dongiga"
@decap_trainer_name TRAINER_DANAPIX, "Danapix"
@decap_trainer_name TRAINER_ERIN, "Erin"
@decap_trainer_name TRAINER_MEADOWBREAK, "Meadowbreak"
@decap_trainer_name TRAINER_BAKANEKO, "Baka Neko"
@decap_trainer_name TRAINER_KAYLEE, "Kaylee"
@decap_trainer_name TRAINER_BALBOON, "Balboon"
@decap_trainer_name TRAINER_DARCY, "Darcy"
@decap_trainer_name TRAINER_JENNY_1, "Jenny"
@decap_trainer_name TRAINER_JENNY_2, "Jenny"
@decap_trainer_name TRAINER_JENNY_3, "Jenny"
@decap_trainer_name TRAINER_JENNY_4, "Jenny"
@decap_trainer_name TRAINER_NAKAJIMA, "Nakajima"
@decap_trainer_name TRAINER_SHIZUO, "Shizuo"
@decap_trainer_name TRAINER_LENNA, "Lenna"
@decap_trainer_name TRAINER_FOOTMAN_10, "Footman"
@decap_trainer_name TRAINER_MARTHA, "Martha"
@decap_trainer_name TRAINER_YONGSHUI, "Yong Shui"
@decap_trainer_name TRAINER_NINA, "Nina"
@decap_trainer_name TRAINER_RYUUGAMINE, "Ryuugamine"
@decap_trainer_name TRAINER_DIANA_1, "Diana"
@decap_trainer_name TRAINER_DIANA_2, "Diana"
@decap_trainer_name TRAINER_DIANA_3, "Diana"
@decap_trainer_name TRAINER_DIANA_4, "Diana"
@decap_trainer_name TRAINER_AKAGI, "Akagi"
@decap_trainer_name TRAINER_AMYANDLIV_1, "Amy & Liv"
@decap_trainer_name TRAINER_DOUGANDLOLA, "Doug & Lola"
@decap_trainer_name TRAINER_MIRAI, "Mirai"
@decap_trainer_name TRAINER_AMYANDLIV_2, "Amy & Liv"
@decap_trainer_name TRAINER_GINAANDMIA, "Gina & Mia"
@decap_trainer_name TRAINER_AMYANDLIV_3, "Amy & Liv"
@decap_trainer_name TRAINER_AMYANDLIV_4, "Amy & Liv"
@decap_trainer_name TRAINER_AMYANDLIV_5, "Amy & Liv"
@decap_trainer_name TRAINER_PIOUS, "Pious"
@decap_trainer_name TRAINER_BARRABAS, "Barrabas"
@decap_trainer_name TRAINER_ERNEST_1, "Ernest"
@decap_trainer_name TRAINER_DWAYNE, "Dwayne"
@decap_trainer_name TRAINER_PHILLIP, "Phillip"
@decap_trainer_name TRAINER_LEONARD, "Leonard"
@decap_trainer_name TRAINER_FORMAGGIO, "Formaggio"
@decap_trainer_name TRAINER_ERNEST_2, "Ernest"
@decap_trainer_name TRAINER_ERNEST_3, "Ernest"
@decap_trainer_name TRAINER_ERNEST_4, "Ernest"
@decap_trainer_name TRAINER_ERNEST_5, "Ernest"
@decap_trainer_name TRAINER__1, ""
@decap_trainer_name TRAINER__2, ""
@decap_trainer_name TRAINER__3, ""
@decap_trainer_name TRAINER_SONNY, "Sonny"
@decap_trainer_name TRAINER_DONOVAN, "Donovan"
@decap_trainer_name TRAINER_GERALD, "Gerald"
@decap_trainer_name TRAINER_KELVIN, "Kelvin"
@decap_trainer_name TRAINER_KODY, "Kody"
@decap_trainer_name TRAINER_TEVIN, "Tevin"
@decap_trainer_name TRAINER_DAMON, "Damon"
@decap_trainer_name TRAINER_PABLO, "Pablo"
@decap_trainer_name TRAINER_FOOTMAN_11, "Footman"
@decap_trainer_name TRAINER_HECTOR_1, "Hector"
@decap_trainer_name TRAINER_HECTOR_2, "Hector"
@decap_trainer_name TRAINER_EDWIN_1, "Edwin"
@decap_trainer_name TRAINER_EDWIN_2, "Edwin"
@decap_trainer_name TRAINER_EDWIN_3, "Edwin"
@decap_trainer_name TRAINER_EDWIN_4, "Edwin"
@decap_trainer_name TRAINER_TEMULENCE_3, "Temulence"
@decap_trainer_name TRAINER_BERT, "Bert"
@decap_trainer_name TRAINER_BRENDAN_1, "Brendan"
@decap_trainer_name TRAINER_BRENDAN_2, "Brendan"
@decap_trainer_name TRAINER_BRENDAN_3, "Brendan"
@decap_trainer_name TRAINER_BRENDAN_4, "Brendan"
@decap_trainer_name TRAINER_BRENDAN_5, "Brendan"
@decap_trainer_name TRAINER_BRENDAN_6, "Brendan"
@decap_trainer_name TRAINER_BRENDAN_7, "Brendan"
@decap_trainer_name TRAINER_BRENDAN_8, "Brendan"
@decap_trainer_name TRAINER_ALICIA_UNKNOWN, "???"
@decap_trainer_name TRAINER_ALICIA_1, "Alicia"
@decap_trainer_name TRAINER_ALICIA_2, "Alicia"
@decap_trainer_name TRAINER_WAR, "War"
@decap_trainer_name TRAINER_MAY_1, "May"
@decap_trainer_name TRAINER_MAY_2, "May"
@decap_trainer_name TRAINER_MAY_3, "May"
@decap_trainer_name TRAINER_MAY_4, "May"
@decap_trainer_name TRAINER_MAY_5, "May"
@decap_trainer_name TRAINER_ISAAC_1, "Isaac"
@decap_trainer_name TRAINER_RILEY, "Riley"
@decap_trainer_name TRAINER_AIDAN, "Aidan"
@decap_trainer_name TRAINER_ISAAC_2, "Isaac"
@decap_trainer_name TRAINER_ISAAC_3, "Isaac"
@decap_trainer_name TRAINER_ISAAC_4, "Isaac"
@decap_trainer_name TRAINER_ISAAC_5, "Isaac"
@decap_trainer_name TRAINER_HIROAKI, "Hiroaki"
@decap_trainer_name TRAINER_ALEXIA, "Alexia"
@decap_trainer_name TRAINER_DANIELLE, "Danielle"
@decap_trainer_name TRAINER_LYDIA_1, "Lydia"
@decap_trainer_name TRAINER_LYDIA_2, "Lydia"
@decap_trainer_name TRAINER_LYDIA_3, "Lydia"
@decap_trainer_name TRAINER_LYDIA_4, "Lydia"
@decap_trainer_name TRAINER_YULVARIN, "Yul Varin"
@decap_trainer_name TRAINER_SWINEWITCH, "Swine Witch"
@decap_trainer_name TRAINER_SEBASTIAN, "Sebastian"
@decap_trainer_name TRAINER_JACKSON_1, "Jackson"
@decap_trainer_name TRAINER_JACKSON_2, "Jackson"
@decap_trainer_name TRAINER_JACKSON_3, "Jackson"
@decap_trainer_name TRAINER_JACKSON_4, "Jackson"
@decap_trainer_name TRAINER_CATHERINE_1, "Catherine"
@decap_trainer_name TRAINER_TOOTHWITCH, "Tooth Witch"
@decap_trainer_name TRAINER_SOPHIA, "Sophia"
@decap_trainer_name TRAINER_CATHERINE_2, "Catherine"
@decap_trainer_name TRAINER_SALARYMAN_1, "Salaryman"
@decap_trainer_name TRAINER_CATHERINE_3, "Catherine"
@decap_trainer_name TRAINER_CATHERINE_4, "Catherine"
@decap_trainer_name TRAINER_TEMULENCE_4, "Temulence"
@decap_trainer_name TRAINER_FOOTMAN_12, "Footman"
@decap_trainer_name TRAINER_SALARYMAN_2, "Salaryman"
@decap_trainer_name TRAINER_FOOTMAN_13, "Footman"
@decap_trainer_name TRAINER_SALARYMAN_3, "Salaryman"
@decap_trainer_name TRAINER_GRUNT_1, "Grunt"
@decap_trainer_name TRAINER_GRUNT_2, "Grunt"
@decap_trainer_name TRAINER_GRUNT_3, "Grunt"
@decap_trainer_name TRAINER_GRUNT_4, "Grunt"
@decap_trainer_name TRAINER_ZABULON, "Zabulon"
@decap_trainer_name TRAINER_GRUNT_5, "Grunt"
@decap_trainer_name TRAINER_GRUNT_6, "Grunt"
@decap_trainer_name TRAINER_GRUNT_7, "Grunt"
@decap_trainer_name TRAINER_GRUNT_8, "Grunt"
@decap_trainer_name TRAINER_GRUNT_9, "Grunt"
@decap_trainer_name TRAINER_BELIAL_2, "Belial"
@decap_trainer_name TRAINER_MIGHT, "Might"
@decap_trainer_name TRAINER_GRUNT_10, "Grunt"
@decap_trainer_name TRAINER_GRUNT_11, "Grunt"
@decap_trainer_name TRAINER_GRUNT_12, "Grunt"
@decap_trainer_name TRAINER_GRUNT_13, "Grunt"
@decap_trainer_name TRAINER_GRUNT_14, "Grunt"
@decap_trainer_name TRAINER_GRUNT_15, "Grunt"
@decap_trainer_name TRAINER_GRUNT_16, "Grunt"
@decap_trainer_name TRAINER_GRUNT_17, "Grunt"
@decap_trainer_name TRAINER_LINDA, "Linda"
@decap_trainer_name TRAINER_SALARYMAN_4, "Salaryman"
@decap_trainer_name TRAINER_SALARYMAN_5, "Salaryman"
@decap_trainer_name TRAINER_KENT, "Kent"
@decap_trainer_name TRAINER_PESTILENCE, "Pestilence"
@decap_trainer_name TRAINER_SALARYMAN_6, "Salaryman"
@decap_trainer_name TRAINER_TABITHA, "Tabitha"
@decap_trainer_name TRAINER_SHADERU, "Shaderu"
@decap_trainer_name TRAINER_GLEIS_3, "Gleis"
@decap_trainer_name TRAINER_COURTNEY, "Courtney"
@decap_trainer_name TRAINER_MAXIE_1, "Maxie"
@decap_trainer_name TRAINER_MAXIE_2, "Maxie"
@decap_trainer_name TRAINER_TIANA, "Tiana"
@decap_trainer_name TRAINER_HARVEY_2, "Harvey"
@decap_trainer_name TRAINER_JANICE, "Janice"
@decap_trainer_name TRAINER_MUGWIN_4, "Mugwin"
@decap_trainer_name TRAINER_HALEY_1, "Haley"
@decap_trainer_name TRAINER_HALEY_2, "Haley"
@decap_trainer_name TRAINER_HALEY_3, "Haley"
@decap_trainer_name TRAINER_HALEY_4, "Haley"
@decap_trainer_name TRAINER_SALLY, "Sally"
@decap_trainer_name TRAINER_ROBIN, "Robin"
@decap_trainer_name TRAINER_ANDREA, "Andrea"
@decap_trainer_name TRAINER_CRISSY, "Crissy"
@decap_trainer_name TRAINER_RICA, "Rica"
@decap_trainer_name TRAINER_LYLE, "Lyle"
@decap_trainer_name TRAINER_JOSE, "Jose"
@decap_trainer_name TRAINER_DOUG, "Doug"
@decap_trainer_name TRAINER_TOMMO, "Tommo"
@decap_trainer_name TRAINER_CINNABAR, "Cinnabar"
@decap_trainer_name TRAINER_ANDROMALIUS, "Andromalius"
@decap_trainer_name TRAINER_JAMES_1, "James"
@decap_trainer_name TRAINER_FLOATZEL, "Floatzel"
@decap_trainer_name TRAINER_JAMES_2, "James"
@decap_trainer_name TRAINER_JAMES_3, "James"
@decap_trainer_name TRAINER_KLOTHOK, "Klo'Thok"
@decap_trainer_name TRAINER_RAAKOR, "Raa'Kor"
@decap_trainer_name TRAINER_LENNY, "Lenny"
@decap_trainer_name TRAINER_LUCAS_1, "Lucas"
@decap_trainer_name TRAINER_ALAN, "Alan"
@decap_trainer_name TRAINER_CLARK, "Clark"
@decap_trainer_name TRAINER_FENGDARIN, "Feng Darin"
@decap_trainer_name TRAINER_LUCAS_2, "Lucas"
@decap_trainer_name TRAINER_BRENTFORD, "Brentford"
@decap_trainer_name TRAINER_HERO, "Hero"
@decap_trainer_name TRAINER_TRENT_1, "Trent"
@decap_trainer_name TRAINER_ZUUL, "Zuul"
@decap_trainer_name TRAINER_KYLIE, "Kylie"
@decap_trainer_name TRAINER_TRENT_2, "Trent"
@decap_trainer_name TRAINER_MAIANDHIRO, "Mai & Hiro"
@decap_trainer_name TRAINER_LEAANDJED, "Lea & Jed"
@decap_trainer_name TRAINER_LOLAANDLUTE, "Lola & Lute"
@decap_trainer_name TRAINER_LOISANDHAL_1, "Lois & Hal"
@decap_trainer_name TRAINER_LOISANDHAL_2, "Lois & Hal"
@decap_trainer_name TRAINER_LOISANDHAL_3, "Lois & Hal"
@decap_trainer_name TRAINER_LOISANDHAL_4, "Lois & Hal"
@decap_trainer_name TRAINER_JOHANNA, "Johanna"
@decap_trainer_name TRAINER_MEILIN, "Mei Lin"
@decap_trainer_name TRAINER_VIVIAN, "Vivian"
@decap_trainer_name TRAINER_NIANZHU, "Nianzhu"
@decap_trainer_name TRAINER_SIOBHAN, "Siobhan"
@decap_trainer_name TRAINER_WITCH, "Witch"
@decap_trainer_name TRAINER_SANDWITCH, "Sand Witch"
@decap_trainer_name TRAINER_ASPHODEL, "Asphodel"
@decap_trainer_name TRAINER_LEOZAR, "Leozar"
@decap_trainer_name TRAINER_GLEIS_4, "Gleis"
@decap_trainer_name TRAINER_SPUTNOV_4, "Sputnov"
@decap_trainer_name TRAINER_VLADOV_4, "Vladov"
@decap_trainer_name TRAINER_ADOLV_4, "Adolv"
@decap_trainer_name TRAINER_CHIEF, "Chief"
@decap_trainer_name TRAINER_BRENDAN_9, "Brendan"
@decap_trainer_name TRAINER_PYRITE, "Pyrite"
@decap_trainer_name TRAINER_BRENDAN_10, "Brendan"
@decap_trainer_name TRAINER_MAY_6, "May"
@decap_trainer_name TRAINER_MAY_7, "May"
@decap_trainer_name TRAINER_SENEX_2, "Senex"
@decap_trainer_name TRAINER_BURNAGGIO, "Burnaggio"
@decap_trainer_name TRAINER_FROZONE, "Frozone"
@decap_trainer_name TRAINER_PARALISI, "Paralisi"
@decap_trainer_name TRAINER_JOURDELAYS, "Jourdelays"
@decap_trainer_name TRAINER_MSDOLITTLE, "Ms Dolittle"
@decap_trainer_name TRAINER_ULTRAKICK, "Ultra Kick"
@decap_trainer_name TRAINER_WAYNEFLETE, "Wayneflete"
@decap_trainer_name TRAINER_DYNAMO, "Dynamo"
@decap_trainer_name TRAINER_ICIKLING, "Icikling"
@decap_trainer_name TRAINER_TRISHA, "Trisha"
@decap_trainer_name TRAINER_KENANDBEL, "Ken & Bel"
@decap_trainer_name TRAINER_KIMANDIRIS, "Kim & Iris"
@decap_trainer_name TRAINER_DOUBLEACT_3, "Double Act"
@decap_trainer_name TRAINER_JANANDJON, "Jan & Jon"
@decap_trainer_name TRAINER_JOHNANDJAY_1, "John & Jay"
@decap_trainer_name TRAINER_JOHNANDJAY_2, "John & Jay"
@decap_trainer_name TRAINER_JOHNANDJAY_3, "John & Jay"
@decap_trainer_name TRAINER_JOHNANDJAY_4, "John & Jay"
@decap_trainer_name TRAINER_JOHNANDJAY_5, "John & Jay"
@decap_trainer_name TRAINER_HANAANDMIKI, "Hana & Miki"
@decap_trainer_name TRAINER_VENUSANDMILO, "Venus&Milo"
@decap_trainer_name TRAINER_RITAANDSAM_1, "Rita & Sam"
@decap_trainer_name TRAINER_RITAANDSAM_2, "Rita & Sam"
@decap_trainer_name TRAINER_RITAANDSAM_3, "Rita & Sam"
@decap_trainer_name TRAINER_RITAANDSAM_4, "Rita & Sam"
@decap_trainer_name TRAINER_SIMONANDTABBY, "Simon&Tabby"
@decap_trainer_name TRAINER_EUGENE, "Eugene"
