.macro @decap_trainer_class, i, name
@decap_table 0x81f0208, 13, 13, i, name
.endmacro

@decap_trainer_class TRAINER_CLASS_BEAUTY, "Beauty"
@decap_trainer_class TRAINER_CLASS_ROCK_WARRIOR, "Rock Warrior"
@decap_trainer_class TRAINER_CLASS_HAJIKE_KING, "Hajike King"
@decap_trainer_class TRAINER_CLASS_DEATHCALLER, "Deathcaller"
@decap_trainer_class TRAINER_CLASS_ZOMBIE_KID, "Zombie Kid"
@decap_trainer_class TRAINER_CLASS_AROMA_LADY, "Aroma Lady"
@decap_trainer_class TRAINER_CLASS_GHOST_GIRL, "Ghost Girl"
@decap_trainer_class TRAINER_CLASS_STOWAWAY, "Stowaway"
@decap_trainer_class TRAINER_CLASS_SIX_ELEMENTS, "Six Elements"
@decap_trainer_class TRAINER_CLASS_LEAGUEMASTER, "Leaguemaster"
@decap_trainer_class TRAINER_CLASS_NORMAL_GIRL, "Normal Girl"
@decap_trainer_class TRAINER_CLASS_SLIMEMONGER, "Slimemonger"
@decap_trainer_class TRAINER_CLASS_LORD, "Lord"
@decap_trainer_class TRAINER_CLASS_ACTRESS, "Actress"
@decap_trainer_class TRAINER_CLASS_PIRATE, "Pirate"
@decap_trainer_class TRAINER_CLASS_DEADLY_SEVEN, "Deadly Seven"
@decap_trainer_class TRAINER_CLASS_SWIMMER_M, "Swimmer♂"
@decap_trainer_class TRAINER_CLASS_BLACK_BELT, "Black Belt"
@decap_trainer_class TRAINER_CLASS_ROCKER, "Rocker"
@decap_trainer_class TRAINER_CLASS_TAOIST, "Taoist"
@decap_trainer_class TRAINER_CLASS_FORMER_CHEF, "Former Chef"
@decap_trainer_class TRAINER_CLASS_HEADSLINGER, "Headslinger"
@decap_trainer_class TRAINER_CLASS_LOST_SOUL, "Lost Soul"
@decap_trainer_class TRAINER_CLASS_SEVERED_HEAD, "Severed Head"
@decap_trainer_class TRAINER_CLASS_ELITE_FOUR, "Elite Four"
@decap_trainer_class TRAINER_CLASS_LEADER, "Leader"
@decap_trainer_class TRAINER_CLASS_DRAGON_KING, "Dragon King"
@decap_trainer_class TRAINER_CLASS_DOCTOR, "Doctor"
@decap_trainer_class TRAINER_CLASS_RECRUITERS, "Recruiters"
@decap_trainer_class TRAINER_CLASS_TROLL, "Troll"
@decap_trainer_class TRAINER_CLASS_MONSTROUS, "Monstrous"
@decap_trainer_class TRAINER_CLASS_LOOTER, "Looter"
@decap_trainer_class TRAINER_CLASS_CHAMPION, "Champion"
@decap_trainer_class TRAINER_CLASS_FISHERMAN, "Fisherman"
@decap_trainer_class TRAINER_CLASS_SKILLED_CHEF, "Skilled Chef"
@decap_trainer_class TRAINER_CLASS_T_FANGER, "T-fanger"
@decap_trainer_class TRAINER_CLASS_SOLDIER, "Soldier"
@decap_trainer_class TRAINER_CLASS_BATTLEZOMBIE, "Battlezombie"
@decap_trainer_class TRAINER_CLASS_DEMON, "Demon"
@decap_trainer_class TRAINER_CLASS_MIMIC_BROS, "Mimic Bros."
@decap_trainer_class TRAINER_CLASS_SWIMMER_F, "Swimmer♀"
@decap_trainer_class TRAINER_CLASS_SUPPLICANT, "Supplicant"
@decap_trainer_class TRAINER_CLASS_ZOMBIE_DUO, "Zombie Duo"
@decap_trainer_class TRAINER_CLASS_WORLDBREAKER, "Worldbreaker"
@decap_trainer_class TRAINER_CLASS_FILM_STUDENT, "Film Student"
@decap_trainer_class TRAINER_CLASS_THE, "The"
@decap_trainer_class TRAINER_CLASS_WISE_SAGE, "Wise Sage"
@decap_trainer_class TRAINER_CLASS_FROST_DEMON, "Frost Demon"
@decap_trainer_class TRAINER_CLASS_BEST_FRIENDS, "Best Friends"
@decap_trainer_class TRAINER_CLASS_INQUISITION, "Inquisition"
@decap_trainer_class TRAINER_CLASS_DEMON_CORPSE, "Demon Corpse"
@decap_trainer_class TRAINER_CLASS_HORSEMAN, "Horseman"
@decap_trainer_class TRAINER_CLASS_ELDER, "Elder"
@decap_trainer_class TRAINER_CLASS_SURVIVOR, "Survivor"
@decap_trainer_class TRAINER_CLASS_GENTLEMAN, "Gentleman"
@decap_trainer_class TRAINER_CLASS_YOUNG_COUPLE, "Young Couple"
@decap_trainer_class TRAINER_CLASS_FIRESTARTER, "Firestarter"
@decap_trainer_class TRAINER_CLASS_SIS_AND_BRO, "Sis And Bro"