.macro @decap_trainer_class, i, name
.org 0x81f0208 + i * 13
.area 13, 0x0
.string name
.endarea
.endmacro

@decap_trainer_class 0, "Beauty"
@decap_trainer_class 1, "Rock Warrior"
@decap_trainer_class 2, "Hajike King"
@decap_trainer_class 3, "Deathcaller"
@decap_trainer_class 4, "Zombie Kid"
@decap_trainer_class 5, "Aroma Lady"
@decap_trainer_class 6, "Ghost Girl"
@decap_trainer_class 7, "Stowaway"
@decap_trainer_class 8, "Six Elements"
@decap_trainer_class 9, "Leaguemaster"
@decap_trainer_class 10, "Normal Girl"
@decap_trainer_class 11, "Slimemonger"
@decap_trainer_class 12, "Lord"
@decap_trainer_class 13, "Actress"
@decap_trainer_class 14, "Pirate"
@decap_trainer_class 15, "Deadly Seven"
@decap_trainer_class 16, "Swimmer♂"
@decap_trainer_class 17, "Black Belt"
@decap_trainer_class 18, "Rocker"
@decap_trainer_class 19, "Taoist"
@decap_trainer_class 20, "Former Chef"
@decap_trainer_class 21, "Headslinger"
@decap_trainer_class 22, "Lost Soul"
@decap_trainer_class 23, "Severed Head"
@decap_trainer_class 24, "Elite Four"
@decap_trainer_class 25, "Leader"
@decap_trainer_class 26, "Dragon King"
@decap_trainer_class 27, "Doctor"
@decap_trainer_class 28, "Recruiters"
@decap_trainer_class 29, "Troll"
@decap_trainer_class 30, "Monstrous"
@decap_trainer_class 31, "Looter"
@decap_trainer_class 32, "Champion"
@decap_trainer_class 33, "Fisherman"
@decap_trainer_class 34, "Skilled Chef"
@decap_trainer_class 35, "T-fanger"
@decap_trainer_class 36, "Soldier"
@decap_trainer_class 37, "Battlezombie"
@decap_trainer_class 38, "Demon"
@decap_trainer_class 39, "Mimic Bros."
@decap_trainer_class 40, "Swimmer♀"
@decap_trainer_class 41, "Supplicant"
@decap_trainer_class 42, "Zombie Duo"
@decap_trainer_class 43, "Worldbreaker"
@decap_trainer_class 44, "Film Student"
@decap_trainer_class 45, "The"
@decap_trainer_class 46, "Wise Sage"
@decap_trainer_class 47, "Frost Demon"
@decap_trainer_class 48, "Best Friends"
@decap_trainer_class 49, "Inquisition"
@decap_trainer_class 50, "Demon Corpse"
@decap_trainer_class 51, "Horseman"
@decap_trainer_class 52, "Elder"
@decap_trainer_class 53, "Survivor"
@decap_trainer_class 54, "Gentleman"
@decap_trainer_class 55, "Young Couple"
@decap_trainer_class 56, "Firestarter"
@decap_trainer_class 57, "Sis And Bro"